<?php

use Illuminate\Database\Seeder;
use App\Models\Expedicion;
use Illuminate\Support\Facades\DB;

class ExpedicionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('expedicion')->delete();

        Expedicion::insert([
            ['lugar' => 'Medellín' , 'users_id' => 1],
            ['lugar' => 'Abejorral' , 'users_id' => 1],
            ['lugar' => 'Abriaquí' , 'users_id' => 1],
            ['lugar' => 'Alejandría' , 'users_id' => 1],
            ['lugar' => 'Amagá' , 'users_id' => 1],
            ['lugar' => 'Amalfi' , 'users_id' => 1],
            ['lugar' => 'Andes' , 'users_id' => 1],
            ['lugar' => 'Angelópolis' , 'users_id' => 1],
            ['lugar' => 'Angostura' , 'users_id' => 1],
            ['lugar' => 'Anorí' , 'users_id' => 1],
            ['lugar' => 'Chimá' , 'users_id' => 1],
            ['lugar' => 'Anza' , 'users_id' => 1],
            ['lugar' => 'Apartadó' , 'users_id' => 1],
            ['lugar' => 'Arboletes' , 'users_id' => 1],
            ['lugar' => 'Argelia' , 'users_id' => 1],
            ['lugar' => 'Armenia' , 'users_id' => 1],
            ['lugar' => 'Barbosa' , 'users_id' => 1],
            ['lugar' => 'Bello' , 'users_id' => 1],
            ['lugar' => 'Betania' , 'users_id' => 1],
            ['lugar' => 'Betulia' , 'users_id' => 1],
            ['lugar' => 'Ciudad Bolívar' , 'users_id' => 1],
            ['lugar' => 'Briceño' , 'users_id' => 1],
            ['lugar' => 'Buriticá' , 'users_id' => 1],
            ['lugar' => 'Cáceres' , 'users_id' => 1],
            ['lugar' => 'Caicedo' , 'users_id' => 1],
            ['lugar' => 'Caldas' , 'users_id' => 1],
            ['lugar' => 'Campamento' , 'users_id' => 1],
            ['lugar' => 'Cañasgordas' , 'users_id' => 1],
            ['lugar' => 'Caracolí' , 'users_id' => 1],
            ['lugar' => 'Caramanta' , 'users_id' => 1],
            ['lugar' => 'Carepa' , 'users_id' => 1],
            ['lugar' => 'Sampués' , 'users_id' => 1],
            ['lugar' => 'Carolina' , 'users_id' => 1],
            ['lugar' => 'Caucasia' , 'users_id' => 1],
            ['lugar' => 'Chigorodó' , 'users_id' => 1],
            ['lugar' => 'Cisneros' , 'users_id' => 1],
            ['lugar' => 'Cocorná' , 'users_id' => 1],
            ['lugar' => 'Concepción' , 'users_id' => 1],
            ['lugar' => 'Concordia' , 'users_id' => 1],
            ['lugar' => 'Copacabana' , 'users_id' => 1],
            ['lugar' => 'Dabeiba' , 'users_id' => 1],
            ['lugar' => 'Don Matías' , 'users_id' => 1],
            ['lugar' => 'Ebéjico' , 'users_id' => 1],
            ['lugar' => 'El Bagre' , 'users_id' => 1],
            ['lugar' => 'Entrerrios' , 'users_id' => 1],
            ['lugar' => 'Envigado' , 'users_id' => 1],
            ['lugar' => 'Fredonia' , 'users_id' => 1],
            ['lugar' => 'Giraldo' , 'users_id' => 1],
            ['lugar' => 'Girardota' , 'users_id' => 1],
            ['lugar' => 'Gómez Plata' , 'users_id' => 1],
            ['lugar' => 'Nunchía' , 'users_id' => 1],
            ['lugar' => 'Guadalupe' , 'users_id' => 1],
            ['lugar' => 'Guarne' , 'users_id' => 1],
            ['lugar' => 'Guatapé' , 'users_id' => 1],
            ['lugar' => 'Heliconia' , 'users_id' => 1],
            ['lugar' => 'Hispania' , 'users_id' => 1],
            ['lugar' => 'Itagui' , 'users_id' => 1],
            ['lugar' => 'Ituango' , 'users_id' => 1],
            ['lugar' => 'Pamplona' , 'users_id' => 1],
            ['lugar' => 'Jericó' , 'users_id' => 1],
            ['lugar' => 'La Ceja' , 'users_id' => 1],
            ['lugar' => 'La Estrella' , 'users_id' => 1],
            ['lugar' => 'La Pintada' , 'users_id' => 1],
            ['lugar' => 'La Unión' , 'users_id' => 1],
            ['lugar' => 'Liborina' , 'users_id' => 1],
            ['lugar' => 'Maceo' , 'users_id' => 1],
            ['lugar' => 'Marinilla' , 'users_id' => 1],
            ['lugar' => 'Montebello' , 'users_id' => 1],
            ['lugar' => 'Murindó' , 'users_id' => 1],
            ['lugar' => 'Mutatá' , 'users_id' => 1],
            ['lugar' => 'Nariño' , 'users_id' => 1],
            ['lugar' => 'Necoclí' , 'users_id' => 1],
            ['lugar' => 'Nechí' , 'users_id' => 1],
            ['lugar' => 'Olaya' , 'users_id' => 1],
            ['lugar' => 'Peñol' , 'users_id' => 1],
            ['lugar' => 'Peque' , 'users_id' => 1],
            ['lugar' => 'Pueblorrico' , 'users_id' => 1],
            ['lugar' => 'Puerto Berrío' , 'users_id' => 1],
            ['lugar' => 'Puerto Nare' , 'users_id' => 1],
            ['lugar' => 'Puerto Triunfo' , 'users_id' => 1],
            ['lugar' => 'Remedios' , 'users_id' => 1],
            ['lugar' => 'Retiro' , 'users_id' => 1],
            ['lugar' => 'Rionegro' , 'users_id' => 1],
            ['lugar' => 'Sabanalarga' , 'users_id' => 1],
            ['lugar' => 'Sabaneta' , 'users_id' => 1],
            ['lugar' => 'Salgar' , 'users_id' => 1],
            ['lugar' => 'Albán' , 'users_id' => 1],
            ['lugar' => 'Yavaraté' , 'users_id' => 1],
            ['lugar' => 'San Francisco' , 'users_id' => 1],
            ['lugar' => 'San Jerónimo' , 'users_id' => 1],
            ['lugar' => 'Montelíbano' , 'users_id' => 1],
            ['lugar' => 'Puerto Asís' , 'users_id' => 1],
            ['lugar' => 'San Luis' , 'users_id' => 1],
            ['lugar' => 'San Pedro' , 'users_id' => 1],
            ['lugar' => 'Corozal' , 'users_id' => 1],
            ['lugar' => 'San Rafael' , 'users_id' => 1],
            ['lugar' => 'San Roque' , 'users_id' => 1],
            ['lugar' => 'San Vicente' , 'users_id' => 1],
            ['lugar' => 'Santa Bárbara' , 'users_id' => 1],
            ['lugar' => 'Buesaco' , 'users_id' => 1],
            ['lugar' => 'Santo Domingo' , 'users_id' => 1],
            ['lugar' => 'El Santuario' , 'users_id' => 1],
            ['lugar' => 'Segovia' , 'users_id' => 1],
            ['lugar' => 'Sopetrán' , 'users_id' => 1],
            ['lugar' => 'Támesis' , 'users_id' => 1],
            ['lugar' => 'Tarazá' , 'users_id' => 1],
            ['lugar' => 'Tarso' , 'users_id' => 1],
            ['lugar' => 'Titiribí' , 'users_id' => 1],
            ['lugar' => 'Toledo' , 'users_id' => 1],
            ['lugar' => 'Turbo' , 'users_id' => 1],
            ['lugar' => 'Uramita' , 'users_id' => 1],
            ['lugar' => 'Urrao' , 'users_id' => 1],
            ['lugar' => 'Valdivia' , 'users_id' => 1],
            ['lugar' => 'Valparaíso' , 'users_id' => 1],
            ['lugar' => 'Vegachí' , 'users_id' => 1],
            ['lugar' => 'Venecia' , 'users_id' => 1],
            ['lugar' => 'Maní' , 'users_id' => 1],
            ['lugar' => 'Yalí' , 'users_id' => 1],
            ['lugar' => 'Yarumal' , 'users_id' => 1],
            ['lugar' => 'Yolombó' , 'users_id' => 1],
            ['lugar' => 'Yondó' , 'users_id' => 1],
            ['lugar' => 'Zaragoza' , 'users_id' => 1],
            ['lugar' => 'Barranquilla' , 'users_id' => 1],
            ['lugar' => 'Baranoa' , 'users_id' => 1],
            ['lugar' => 'El Peñón' , 'users_id' => 1],
            ['lugar' => 'Candelaria' , 'users_id' => 1],
            ['lugar' => 'Galapa' , 'users_id' => 1],
            ['lugar' => 'Tuluá' , 'users_id' => 1],
            ['lugar' => 'Casabianca' , 'users_id' => 1],
            ['lugar' => 'Luruaco' , 'users_id' => 1],
            ['lugar' => 'Malambo' , 'users_id' => 1],
            ['lugar' => 'Manatí' , 'users_id' => 1],
            ['lugar' => 'Anolaima' , 'users_id' => 1],
            ['lugar' => 'Piojó' , 'users_id' => 1],
            ['lugar' => 'Polonuevo' , 'users_id' => 1],
            ['lugar' => 'Chía' , 'users_id' => 1],
            ['lugar' => 'San Andrés de Tumaco' , 'users_id' => 1],
            ['lugar' => 'Sabanagrande' , 'users_id' => 1],
            ['lugar' => 'Sabanalarga' , 'users_id' => 1],
            ['lugar' => 'Santa Lucía' , 'users_id' => 1],
            ['lugar' => 'Santo Tomás' , 'users_id' => 1],
            ['lugar' => 'Soledad' , 'users_id' => 1],
            ['lugar' => 'Suan' , 'users_id' => 1],
            ['lugar' => 'Tubará' , 'users_id' => 1],
            ['lugar' => 'Usiacurí' , 'users_id' => 1],
            ['lugar' => 'Milán' , 'users_id' => 1],
            ['lugar' => 'Capitanejo' , 'users_id' => 1],
            ['lugar' => 'Achí' , 'users_id' => 1],
            ['lugar' => 'Anzoátegui' , 'users_id' => 1],
            ['lugar' => 'Arenal' , 'users_id' => 1],
            ['lugar' => 'Arjona' , 'users_id' => 1],
            ['lugar' => 'Arroyohondo' , 'users_id' => 1],
            ['lugar' => 'Florida' , 'users_id' => 1],
            ['lugar' => 'Calamar' , 'users_id' => 1],
            ['lugar' => 'Cantagallo' , 'users_id' => 1],
            ['lugar' => 'Cicuco' , 'users_id' => 1],
            ['lugar' => 'Córdoba' , 'users_id' => 1],
            ['lugar' => 'Clemencia' , 'users_id' => 1],
            ['lugar' => 'Repelón' , 'users_id' => 1],
            ['lugar' => 'El Guamo' , 'users_id' => 1],
            ['lugar' => 'Frontino' , 'users_id' => 1],
            ['lugar' => 'Magangué' , 'users_id' => 1],
            ['lugar' => 'Mahates' , 'users_id' => 1],
            ['lugar' => 'Margarita' , 'users_id' => 1],
            ['lugar' => 'Montecristo' , 'users_id' => 1],
            ['lugar' => 'Mompós' , 'users_id' => 1],
            ['lugar' => 'Morales' , 'users_id' => 1],
            ['lugar' => 'Norosí' , 'users_id' => 1],
            ['lugar' => 'Pinillos' , 'users_id' => 1],
            ['lugar' => 'Regidor' , 'users_id' => 1],
            ['lugar' => 'Río Viejo' , 'users_id' => 1],
            ['lugar' => 'San Estanislao' , 'users_id' => 1],
            ['lugar' => 'San Fernando' , 'users_id' => 1],
            ['lugar' => 'El Peñón' , 'users_id' => 1],
            ['lugar' => 'Pamplonita' , 'users_id' => 1],
            ['lugar' => 'San Juan Nepomuceno' , 'users_id' => 1],
            ['lugar' => 'Miriti Paraná' , 'users_id' => 1],
            ['lugar' => 'Támara' , 'users_id' => 1],
            ['lugar' => 'Santa Catalina' , 'users_id' => 1],
            ['lugar' => 'Santa Rosa' , 'users_id' => 1],
            ['lugar' => 'Tibasosa' , 'users_id' => 1],
            ['lugar' => 'Simití' , 'users_id' => 1],
            ['lugar' => 'Soplaviento' , 'users_id' => 1],
            ['lugar' => 'Talaigua Nuevo' , 'users_id' => 1],
            ['lugar' => 'Tiquisio' , 'users_id' => 1],
            ['lugar' => 'Turbaco' , 'users_id' => 1],
            ['lugar' => 'Turbaná' , 'users_id' => 1],
            ['lugar' => 'Villanueva' , 'users_id' => 1],
            ['lugar' => 'Páez' , 'users_id' => 1],
            ['lugar' => 'Tunja' , 'users_id' => 1],
            ['lugar' => 'Almeida' , 'users_id' => 1],
            ['lugar' => 'Aquitania' , 'users_id' => 1],
            ['lugar' => 'Arcabuco' , 'users_id' => 1],
            ['lugar' => 'Ibagué' , 'users_id' => 1],
            ['lugar' => 'Berbeo' , 'users_id' => 1],
            ['lugar' => 'Betéitiva' , 'users_id' => 1],
            ['lugar' => 'Boavita' , 'users_id' => 1],
            ['lugar' => 'Boyacá' , 'users_id' => 1],
            ['lugar' => 'Briceño' , 'users_id' => 1],
            ['lugar' => 'Buena Vista' , 'users_id' => 1],
            ['lugar' => 'Busbanzá' , 'users_id' => 1],
            ['lugar' => 'Caldas' , 'users_id' => 1],
            ['lugar' => 'Campohermoso' , 'users_id' => 1],
            ['lugar' => 'Cerinza' , 'users_id' => 1],
            ['lugar' => 'Chinavita' , 'users_id' => 1],
            ['lugar' => 'Chiquinquirá' , 'users_id' => 1],
            ['lugar' => 'Chiscas' , 'users_id' => 1],
            ['lugar' => 'Chita' , 'users_id' => 1],
            ['lugar' => 'Chitaraque' , 'users_id' => 1],
            ['lugar' => 'Chivatá' , 'users_id' => 1],
            ['lugar' => 'Cómbita' , 'users_id' => 1],
            ['lugar' => 'Coper' , 'users_id' => 1],
            ['lugar' => 'Corrales' , 'users_id' => 1],
            ['lugar' => 'Covarachía' , 'users_id' => 1],
            ['lugar' => 'Cubará' , 'users_id' => 1],
            ['lugar' => 'Cucaita' , 'users_id' => 1],
            ['lugar' => 'Cuítiva' , 'users_id' => 1],
            ['lugar' => 'Chíquiza' , 'users_id' => 1],
            ['lugar' => 'Chivor' , 'users_id' => 1],
            ['lugar' => 'Duitama' , 'users_id' => 1],
            ['lugar' => 'El Cocuy' , 'users_id' => 1],
            ['lugar' => 'El Espino' , 'users_id' => 1],
            ['lugar' => 'Firavitoba' , 'users_id' => 1],
            ['lugar' => 'Floresta' , 'users_id' => 1],
            ['lugar' => 'Gachantivá' , 'users_id' => 1],
            ['lugar' => 'Gameza' , 'users_id' => 1],
            ['lugar' => 'Garagoa' , 'users_id' => 1],
            ['lugar' => 'Guacamayas' , 'users_id' => 1],
            ['lugar' => 'Guateque' , 'users_id' => 1],
            ['lugar' => 'Guayatá' , 'users_id' => 1],
            ['lugar' => 'Güicán' , 'users_id' => 1],
            ['lugar' => 'Iza' , 'users_id' => 1],
            ['lugar' => 'Jenesano' , 'users_id' => 1],
            ['lugar' => 'Jericó' , 'users_id' => 1],
            ['lugar' => 'Labranzagrande' , 'users_id' => 1],
            ['lugar' => 'La Capilla' , 'users_id' => 1],
            ['lugar' => 'La Victoria' , 'users_id' => 1],
            ['lugar' => 'Puerto Colombia' , 'users_id' => 1],
            ['lugar' => 'Belén' , 'users_id' => 1],
            ['lugar' => 'Macanal' , 'users_id' => 1],
            ['lugar' => 'Maripí' , 'users_id' => 1],
            ['lugar' => 'Miraflores' , 'users_id' => 1],
            ['lugar' => 'Mongua' , 'users_id' => 1],
            ['lugar' => 'Monguí' , 'users_id' => 1],
            ['lugar' => 'Moniquirá' , 'users_id' => 1],
            ['lugar' => 'Muzo' , 'users_id' => 1],
            ['lugar' => 'Nobsa' , 'users_id' => 1],
            ['lugar' => 'Nuevo Colón' , 'users_id' => 1],
            ['lugar' => 'Oicatá' , 'users_id' => 1],
            ['lugar' => 'Otanche' , 'users_id' => 1],
            ['lugar' => 'Pachavita' , 'users_id' => 1],
            ['lugar' => 'Páez' , 'users_id' => 1],
            ['lugar' => 'Paipa' , 'users_id' => 1],
            ['lugar' => 'Pajarito' , 'users_id' => 1],
            ['lugar' => 'Panqueba' , 'users_id' => 1],
            ['lugar' => 'Pauna' , 'users_id' => 1],
            ['lugar' => 'Paya' , 'users_id' => 1],
            ['lugar' => 'Sopó' , 'users_id' => 1],
            ['lugar' => 'Pesca' , 'users_id' => 1],
            ['lugar' => 'Pisba' , 'users_id' => 1],
            ['lugar' => 'Puerto Boyacá' , 'users_id' => 1],
            ['lugar' => 'Quípama' , 'users_id' => 1],
            ['lugar' => 'Ramiriquí' , 'users_id' => 1],
            ['lugar' => 'Ráquira' , 'users_id' => 1],
            ['lugar' => 'Rondón' , 'users_id' => 1],
            ['lugar' => 'Saboyá' , 'users_id' => 1],
            ['lugar' => 'Sáchica' , 'users_id' => 1],
            ['lugar' => 'Samacá' , 'users_id' => 1],
            ['lugar' => 'San Eduardo' , 'users_id' => 1],
            ['lugar' => 'Carmen del Darien' , 'users_id' => 1],
            ['lugar' => 'Gama' , 'users_id' => 1],
            ['lugar' => 'San Mateo' , 'users_id' => 1],
            ['lugar' => 'Sasaima' , 'users_id' => 1],
            ['lugar' => 'Chachagüí' , 'users_id' => 1],
            ['lugar' => 'Santana' , 'users_id' => 1],
            ['lugar' => 'Santa María' , 'users_id' => 1],
            ['lugar' => 'Cúcuta' , 'users_id' => 1],
            ['lugar' => 'Santa Sofía' , 'users_id' => 1],
            ['lugar' => 'Sativanorte' , 'users_id' => 1],
            ['lugar' => 'Sativasur' , 'users_id' => 1],
            ['lugar' => 'Siachoque' , 'users_id' => 1],
            ['lugar' => 'Soatá' , 'users_id' => 1],
            ['lugar' => 'Socotá' , 'users_id' => 1],
            ['lugar' => 'Socha' , 'users_id' => 1],
            ['lugar' => 'Sogamoso' , 'users_id' => 1],
            ['lugar' => 'Somondoco' , 'users_id' => 1],
            ['lugar' => 'Sora' , 'users_id' => 1],
            ['lugar' => 'Sotaquirá' , 'users_id' => 1],
            ['lugar' => 'Soracá' , 'users_id' => 1],
            ['lugar' => 'Susacón' , 'users_id' => 1],
            ['lugar' => 'Sutamarchán' , 'users_id' => 1],
            ['lugar' => 'Sutatenza' , 'users_id' => 1],
            ['lugar' => 'Tasco' , 'users_id' => 1],
            ['lugar' => 'Tenza' , 'users_id' => 1],
            ['lugar' => 'Tibaná' , 'users_id' => 1],
            ['lugar' => 'Tinjacá' , 'users_id' => 1],
            ['lugar' => 'Tipacoque' , 'users_id' => 1],
            ['lugar' => 'Toca' , 'users_id' => 1],
            ['lugar' => 'Cartagena' , 'users_id' => 1],
            ['lugar' => 'Tópaga' , 'users_id' => 1],
            ['lugar' => 'Tota' , 'users_id' => 1],
            ['lugar' => 'Turmequé' , 'users_id' => 1],
            ['lugar' => 'Granada' , 'users_id' => 1],
            ['lugar' => 'Tutazá' , 'users_id' => 1],
            ['lugar' => 'Umbita' , 'users_id' => 1],
            ['lugar' => 'Ventaquemada' , 'users_id' => 1],
            ['lugar' => 'Viracachá' , 'users_id' => 1],
            ['lugar' => 'Zetaquira' , 'users_id' => 1],
            ['lugar' => 'Manizales' , 'users_id' => 1],
            ['lugar' => 'Aguadas' , 'users_id' => 1],
            ['lugar' => 'Anserma' , 'users_id' => 1],
            ['lugar' => 'Aranzazu' , 'users_id' => 1],
            ['lugar' => 'Belalcázar' , 'users_id' => 1],
            ['lugar' => 'Chinchiná' , 'users_id' => 1],
            ['lugar' => 'Filadelfia' , 'users_id' => 1],
            ['lugar' => 'La Dorada' , 'users_id' => 1],
            ['lugar' => 'La Merced' , 'users_id' => 1],
            ['lugar' => 'Manzanares' , 'users_id' => 1],
            ['lugar' => 'Marmato' , 'users_id' => 1],
            ['lugar' => 'Marulanda' , 'users_id' => 1],
            ['lugar' => 'Neira' , 'users_id' => 1],
            ['lugar' => 'Norcasia' , 'users_id' => 1],
            ['lugar' => 'Pácora' , 'users_id' => 1],
            ['lugar' => 'Palestina' , 'users_id' => 1],
            ['lugar' => 'Pensilvania' , 'users_id' => 1],
            ['lugar' => 'Riosucio' , 'users_id' => 1],
            ['lugar' => 'Risaralda' , 'users_id' => 1],
            ['lugar' => 'Salamina' , 'users_id' => 1],
            ['lugar' => 'Samaná' , 'users_id' => 1],
            ['lugar' => 'San José' , 'users_id' => 1],
            ['lugar' => 'Supía' , 'users_id' => 1],
            ['lugar' => 'Victoria' , 'users_id' => 1],
            ['lugar' => 'Villamaría' , 'users_id' => 1],
            ['lugar' => 'Viterbo' , 'users_id' => 1],
            ['lugar' => 'Florencia' , 'users_id' => 1],
            ['lugar' => 'Albania' , 'users_id' => 1],
            ['lugar' => 'Santa Bárbara de Pinto' , 'users_id' => 1],
            ['lugar' => 'María la Baja' , 'users_id' => 1],
            ['lugar' => 'Curillo' , 'users_id' => 1],
            ['lugar' => 'El Doncello' , 'users_id' => 1],
            ['lugar' => 'El Paujil' , 'users_id' => 1],
            ['lugar' => 'Morelia' , 'users_id' => 1],
            ['lugar' => 'Puerto Rico' , 'users_id' => 1],
            ['lugar' => 'La Montañita' , 'users_id' => 1],
            ['lugar' => 'San Vicente del Caguán' , 'users_id' => 1],
            ['lugar' => 'Solano' , 'users_id' => 1],
            ['lugar' => 'Solita' , 'users_id' => 1],
            ['lugar' => 'Valparaíso' , 'users_id' => 1],
            ['lugar' => 'Popayán' , 'users_id' => 1],
            ['lugar' => 'Almaguer' , 'users_id' => 1],
            ['lugar' => 'Argelia' , 'users_id' => 1],
            ['lugar' => 'Balboa' , 'users_id' => 1],
            ['lugar' => 'Bolívar' , 'users_id' => 1],
            ['lugar' => 'Buenos Aires' , 'users_id' => 1],
            ['lugar' => 'Cajibío' , 'users_id' => 1],
            ['lugar' => 'Caldono' , 'users_id' => 1],
            ['lugar' => 'Caloto' , 'users_id' => 1],
            ['lugar' => 'Corinto' , 'users_id' => 1],
            ['lugar' => 'El Tambo' , 'users_id' => 1],
            ['lugar' => 'Florencia' , 'users_id' => 1],
            ['lugar' => 'Guachené' , 'users_id' => 1],
            ['lugar' => 'Guapi' , 'users_id' => 1],
            ['lugar' => 'Inzá' , 'users_id' => 1],
            ['lugar' => 'Jambaló' , 'users_id' => 1],
            ['lugar' => 'La Sierra' , 'users_id' => 1],
            ['lugar' => 'La Vega' , 'users_id' => 1],
            ['lugar' => 'López' , 'users_id' => 1],
            ['lugar' => 'Mercaderes' , 'users_id' => 1],
            ['lugar' => 'Miranda' , 'users_id' => 1],
            ['lugar' => 'Morales' , 'users_id' => 1],
            ['lugar' => 'Padilla' , 'users_id' => 1],
            ['lugar' => 'Patía' , 'users_id' => 1],
            ['lugar' => 'Piamonte' , 'users_id' => 1],
            ['lugar' => 'Piendamó' , 'users_id' => 1],
            ['lugar' => 'Puerto Tejada' , 'users_id' => 1],
            ['lugar' => 'Puracé' , 'users_id' => 1],
            ['lugar' => 'Rosas' , 'users_id' => 1],
            ['lugar' => 'El Peñón' , 'users_id' => 1],
            ['lugar' => 'Jardín' , 'users_id' => 1],
            ['lugar' => 'Santa Rosa' , 'users_id' => 1],
            ['lugar' => 'Silvia' , 'users_id' => 1],
            ['lugar' => 'Sotara' , 'users_id' => 1],
            ['lugar' => 'Suárez' , 'users_id' => 1],
            ['lugar' => 'Sucre' , 'users_id' => 1],
            ['lugar' => 'Timbío' , 'users_id' => 1],
            ['lugar' => 'Timbiquí' , 'users_id' => 1],
            ['lugar' => 'Toribio' , 'users_id' => 1],
            ['lugar' => 'Totoró' , 'users_id' => 1],
            ['lugar' => 'Villa Rica' , 'users_id' => 1],
            ['lugar' => 'Valledupar' , 'users_id' => 1],
            ['lugar' => 'Aguachica' , 'users_id' => 1],
            ['lugar' => 'Agustín Codazzi' , 'users_id' => 1],
            ['lugar' => 'Astrea' , 'users_id' => 1],
            ['lugar' => 'Becerril' , 'users_id' => 1],
            ['lugar' => 'Bosconia' , 'users_id' => 1],
            ['lugar' => 'Chimichagua' , 'users_id' => 1],
            ['lugar' => 'Chiriguaná' , 'users_id' => 1],
            ['lugar' => 'Curumaní' , 'users_id' => 1],
            ['lugar' => 'El Copey' , 'users_id' => 1],
            ['lugar' => 'El Paso' , 'users_id' => 1],
            ['lugar' => 'Gamarra' , 'users_id' => 1],
            ['lugar' => 'González' , 'users_id' => 1],
            ['lugar' => 'La Gloria' , 'users_id' => 1],
            ['lugar' => 'Jamundí' , 'users_id' => 1],
            ['lugar' => 'Manaure' , 'users_id' => 1],
            ['lugar' => 'Pailitas' , 'users_id' => 1],
            ['lugar' => 'Pelaya' , 'users_id' => 1],
            ['lugar' => 'Pueblo Bello' , 'users_id' => 1],
            ['lugar' => 'Tadó' , 'users_id' => 1],
            ['lugar' => 'La Paz' , 'users_id' => 1],
            ['lugar' => 'San Alberto' , 'users_id' => 1],
            ['lugar' => 'San Diego' , 'users_id' => 1],
            ['lugar' => 'San Martín' , 'users_id' => 1],
            ['lugar' => 'Tamalameque' , 'users_id' => 1],
            ['lugar' => 'Montería' , 'users_id' => 1],
            ['lugar' => 'Ayapel' , 'users_id' => 1],
            ['lugar' => 'Buenavista' , 'users_id' => 1],
            ['lugar' => 'Canalete' , 'users_id' => 1],
            ['lugar' => 'Cereté' , 'users_id' => 1],
            ['lugar' => 'Chimá' , 'users_id' => 1],
            ['lugar' => 'Chinú' , 'users_id' => 1],
            ['lugar' => 'Orocué' , 'users_id' => 1],
            ['lugar' => 'Cotorra' , 'users_id' => 1],
            ['lugar' => 'Líbano' , 'users_id' => 1],
            ['lugar' => 'Lorica' , 'users_id' => 1],
            ['lugar' => 'Los Córdobas' , 'users_id' => 1],
            ['lugar' => 'Momil' , 'users_id' => 1],
            ['lugar' => 'Moñitos' , 'users_id' => 1],
            ['lugar' => 'Planeta Rica' , 'users_id' => 1],
            ['lugar' => 'Pueblo Nuevo' , 'users_id' => 1],
            ['lugar' => 'Puerto Escondido' , 'users_id' => 1],
            ['lugar' => 'Yacopí' , 'users_id' => 1],
            ['lugar' => 'Purísima' , 'users_id' => 1],
            ['lugar' => 'Sahagún' , 'users_id' => 1],
            ['lugar' => 'San Andrés Sotavento' , 'users_id' => 1],
            ['lugar' => 'San Antero' , 'users_id' => 1],
            ['lugar' => 'Calarcá' , 'users_id' => 1],
            ['lugar' => 'Sonsón' , 'users_id' => 1],
            ['lugar' => 'El Carmen' , 'users_id' => 1],
            ['lugar' => 'San Pelayo' , 'users_id' => 1],
            ['lugar' => 'Tierralta' , 'users_id' => 1],
            ['lugar' => 'Tuchín' , 'users_id' => 1],
            ['lugar' => 'Valencia' , 'users_id' => 1],
            ['lugar' => 'Lérida' , 'users_id' => 1],
            ['lugar' => 'Anapoima' , 'users_id' => 1],
            ['lugar' => 'Arbeláez' , 'users_id' => 1],
            ['lugar' => 'Beltrán' , 'users_id' => 1],
            ['lugar' => 'Bituima' , 'users_id' => 1],
            ['lugar' => 'Bojacá' , 'users_id' => 1],
            ['lugar' => 'Cabrera' , 'users_id' => 1],
            ['lugar' => 'Cachipay' , 'users_id' => 1],
            ['lugar' => 'Cajicá' , 'users_id' => 1],
            ['lugar' => 'Caparrapí' , 'users_id' => 1],
            ['lugar' => 'Caqueza' , 'users_id' => 1],
            ['lugar' => 'La Apartada' , 'users_id' => 1],
            ['lugar' => 'Chaguaní' , 'users_id' => 1],
            ['lugar' => 'Chipaque' , 'users_id' => 1],
            ['lugar' => 'Choachí' , 'users_id' => 1],
            ['lugar' => 'Chocontá' , 'users_id' => 1],
            ['lugar' => 'Cogua' , 'users_id' => 1],
            ['lugar' => 'Cota' , 'users_id' => 1],
            ['lugar' => 'Cucunubá' , 'users_id' => 1],
            ['lugar' => 'El Colegio' , 'users_id' => 1],
            ['lugar' => 'El Rosal' , 'users_id' => 1],
            ['lugar' => 'Fomeque' , 'users_id' => 1],
            ['lugar' => 'Fosca' , 'users_id' => 1],
            ['lugar' => 'Funza' , 'users_id' => 1],
            ['lugar' => 'Fúquene' , 'users_id' => 1],
            ['lugar' => 'Gachala' , 'users_id' => 1],
            ['lugar' => 'Gachancipá' , 'users_id' => 1],
            ['lugar' => 'Gachetá' , 'users_id' => 1],
            ['lugar' => 'San Cristóbal' , 'users_id' => 1],
            ['lugar' => 'Girardot' , 'users_id' => 1],
            ['lugar' => 'Granada' , 'users_id' => 1],
            ['lugar' => 'Guachetá' , 'users_id' => 1],
            ['lugar' => 'Guaduas' , 'users_id' => 1],
            ['lugar' => 'Guasca' , 'users_id' => 1],
            ['lugar' => 'Guataquí' , 'users_id' => 1],
            ['lugar' => 'Guatavita' , 'users_id' => 1],
            ['lugar' => 'Fusagasugá' , 'users_id' => 1],
            ['lugar' => 'Guayabetal' , 'users_id' => 1],
            ['lugar' => 'Gutiérrez' , 'users_id' => 1],
            ['lugar' => 'Jerusalén' , 'users_id' => 1],
            ['lugar' => 'Junín' , 'users_id' => 1],
            ['lugar' => 'La Calera' , 'users_id' => 1],
            ['lugar' => 'La Mesa' , 'users_id' => 1],
            ['lugar' => 'La Palma' , 'users_id' => 1],
            ['lugar' => 'La Peña' , 'users_id' => 1],
            ['lugar' => 'La Vega' , 'users_id' => 1],
            ['lugar' => 'Lenguazaque' , 'users_id' => 1],
            ['lugar' => 'Macheta' , 'users_id' => 1],
            ['lugar' => 'Madrid' , 'users_id' => 1],
            ['lugar' => 'Manta' , 'users_id' => 1],
            ['lugar' => 'Medina' , 'users_id' => 1],
            ['lugar' => 'Mosquera' , 'users_id' => 1],
            ['lugar' => 'Nariño' , 'users_id' => 1],
            ['lugar' => 'Nemocón' , 'users_id' => 1],
            ['lugar' => 'Nilo' , 'users_id' => 1],
            ['lugar' => 'Nimaima' , 'users_id' => 1],
            ['lugar' => 'Nocaima' , 'users_id' => 1],
            ['lugar' => 'Venecia' , 'users_id' => 1],
            ['lugar' => 'Pacho' , 'users_id' => 1],
            ['lugar' => 'Paime' , 'users_id' => 1],
            ['lugar' => 'Pandi' , 'users_id' => 1],
            ['lugar' => 'Paratebueno' , 'users_id' => 1],
            ['lugar' => 'Pasca' , 'users_id' => 1],
            ['lugar' => 'Puerto Salgar' , 'users_id' => 1],
            ['lugar' => 'Pulí' , 'users_id' => 1],
            ['lugar' => 'Quebradanegra' , 'users_id' => 1],
            ['lugar' => 'Quetame' , 'users_id' => 1],
            ['lugar' => 'Quipile' , 'users_id' => 1],
            ['lugar' => 'Apulo' , 'users_id' => 1],
            ['lugar' => 'Ricaurte' , 'users_id' => 1],
            ['lugar' => 'Zambrano' , 'users_id' => 1],
            ['lugar' => 'San Bernardo' , 'users_id' => 1],
            ['lugar' => 'San Cayetano' , 'users_id' => 1],
            ['lugar' => 'San Francisco' , 'users_id' => 1],
            ['lugar' => 'La Uvita' , 'users_id' => 1],
            ['lugar' => 'Zipaquirá' , 'users_id' => 1],
            ['lugar' => 'Sesquilé' , 'users_id' => 1],
            ['lugar' => 'Sibaté' , 'users_id' => 1],
            ['lugar' => 'Silvania' , 'users_id' => 1],
            ['lugar' => 'Simijaca' , 'users_id' => 1],
            ['lugar' => 'Soacha' , 'users_id' => 1],
            ['lugar' => 'Subachoque' , 'users_id' => 1],
            ['lugar' => 'Suesca' , 'users_id' => 1],
            ['lugar' => 'Supatá' , 'users_id' => 1],
            ['lugar' => 'Susa' , 'users_id' => 1],
            ['lugar' => 'Sutatausa' , 'users_id' => 1],
            ['lugar' => 'Tabio' , 'users_id' => 1],
            ['lugar' => 'Génova' , 'users_id' => 1],
            ['lugar' => 'Tausa' , 'users_id' => 1],
            ['lugar' => 'Tena' , 'users_id' => 1],
            ['lugar' => 'Tenjo' , 'users_id' => 1],
            ['lugar' => 'Tibacuy' , 'users_id' => 1],
            ['lugar' => 'Tibirita' , 'users_id' => 1],
            ['lugar' => 'Tocaima' , 'users_id' => 1],
            ['lugar' => 'Tocancipá' , 'users_id' => 1],
            ['lugar' => 'Topaipí' , 'users_id' => 1],
            ['lugar' => 'Ubalá' , 'users_id' => 1],
            ['lugar' => 'Ubaque' , 'users_id' => 1],
            ['lugar' => 'Suárez' , 'users_id' => 1],
            ['lugar' => 'Une' , 'users_id' => 1],
            ['lugar' => 'Útica' , 'users_id' => 1],
            ['lugar' => 'Castilla la Nueva' , 'users_id' => 1],
            ['lugar' => 'Vianí' , 'users_id' => 1],
            ['lugar' => 'Villagómez' , 'users_id' => 1],
            ['lugar' => 'Villapinzón' , 'users_id' => 1],
            ['lugar' => 'Villeta' , 'users_id' => 1],
            ['lugar' => 'Viotá' , 'users_id' => 1],
            ['lugar' => 'Zipacón' , 'users_id' => 1],
            ['lugar' => 'Quibdó' , 'users_id' => 1],
            ['lugar' => 'Acandí' , 'users_id' => 1],
            ['lugar' => 'Alto Baudo' , 'users_id' => 1],
            ['lugar' => 'Atrato' , 'users_id' => 1],
            ['lugar' => 'Bagadó' , 'users_id' => 1],
            ['lugar' => 'Bahía Solano' , 'users_id' => 1],
            ['lugar' => 'Bajo Baudó' , 'users_id' => 1],
            ['lugar' => 'Belén' , 'users_id' => 1],
            ['lugar' => 'Bojaya' , 'users_id' => 1],
            ['lugar' => 'Unión Panamericana' , 'users_id' => 1],
            ['lugar' => 'Pueblo Viejo' , 'users_id' => 1],
            ['lugar' => 'Cértegui' , 'users_id' => 1],
            ['lugar' => 'Condoto' , 'users_id' => 1],
            ['lugar' => 'Villagarzón' , 'users_id' => 1],
            ['lugar' => 'Facatativá' , 'users_id' => 1],
            ['lugar' => 'Juradó' , 'users_id' => 1],
            ['lugar' => 'Lloró' , 'users_id' => 1],
            ['lugar' => 'Medio Atrato' , 'users_id' => 1],
            ['lugar' => 'Medio Baudó' , 'users_id' => 1],
            ['lugar' => 'Medio San Juan' , 'users_id' => 1],
            ['lugar' => 'Nóvita' , 'users_id' => 1],
            ['lugar' => 'Nuquí' , 'users_id' => 1],
            ['lugar' => 'Río Iro' , 'users_id' => 1],
            ['lugar' => 'Río Quito' , 'users_id' => 1],
            ['lugar' => 'Riosucio' , 'users_id' => 1],
            ['lugar' => 'Puerto Libertador' , 'users_id' => 1],
            ['lugar' => 'Sipí' , 'users_id' => 1],
            ['lugar' => 'Unguía' , 'users_id' => 1],
            ['lugar' => 'Neiva' , 'users_id' => 1],
            ['lugar' => 'Acevedo' , 'users_id' => 1],
            ['lugar' => 'Agrado' , 'users_id' => 1],
            ['lugar' => 'Aipe' , 'users_id' => 1],
            ['lugar' => 'Algeciras' , 'users_id' => 1],
            ['lugar' => 'Altamira' , 'users_id' => 1],
            ['lugar' => 'Baraya' , 'users_id' => 1],
            ['lugar' => 'Campoalegre' , 'users_id' => 1],
            ['lugar' => 'Colombia' , 'users_id' => 1],
            ['lugar' => 'Elías' , 'users_id' => 1],
            ['lugar' => 'Garzón' , 'users_id' => 1],
            ['lugar' => 'Gigante' , 'users_id' => 1],
            ['lugar' => 'Guadalupe' , 'users_id' => 1],
            ['lugar' => 'Hobo' , 'users_id' => 1],
            ['lugar' => 'Iquira' , 'users_id' => 1],
            ['lugar' => 'Isnos' , 'users_id' => 1],
            ['lugar' => 'La Argentina' , 'users_id' => 1],
            ['lugar' => 'La Plata' , 'users_id' => 1],
            ['lugar' => 'Marquetalia' , 'users_id' => 1],
            ['lugar' => 'Nátaga' , 'users_id' => 1],
            ['lugar' => 'Oporapa' , 'users_id' => 1],
            ['lugar' => 'Paicol' , 'users_id' => 1],
            ['lugar' => 'Palermo' , 'users_id' => 1],
            ['lugar' => 'Palestina' , 'users_id' => 1],
            ['lugar' => 'Pital' , 'users_id' => 1],
            ['lugar' => 'Pitalito' , 'users_id' => 1],
            ['lugar' => 'Rivera' , 'users_id' => 1],
            ['lugar' => 'Saladoblanco' , 'users_id' => 1],
            ['lugar' => 'Arboleda' , 'users_id' => 1],
            ['lugar' => 'Santa María' , 'users_id' => 1],
            ['lugar' => 'Suaza' , 'users_id' => 1],
            ['lugar' => 'Tarqui' , 'users_id' => 1],
            ['lugar' => 'Tesalia' , 'users_id' => 1],
            ['lugar' => 'Tello' , 'users_id' => 1],
            ['lugar' => 'Teruel' , 'users_id' => 1],
            ['lugar' => 'Timaná' , 'users_id' => 1],
            ['lugar' => 'Villavieja' , 'users_id' => 1],
            ['lugar' => 'Yaguará' , 'users_id' => 1],
            ['lugar' => 'Riohacha' , 'users_id' => 1],
            ['lugar' => 'Albania' , 'users_id' => 1],
            ['lugar' => 'Barrancas' , 'users_id' => 1],
            ['lugar' => 'Dibula' , 'users_id' => 1],
            ['lugar' => 'Distracción' , 'users_id' => 1],
            ['lugar' => 'El Molino' , 'users_id' => 1],
            ['lugar' => 'Fonseca' , 'users_id' => 1],
            ['lugar' => 'Hatonuevo' , 'users_id' => 1],
            ['lugar' => 'Maicao' , 'users_id' => 1],
            ['lugar' => 'Manaure' , 'users_id' => 1],
            ['lugar' => 'Uribia' , 'users_id' => 1],
            ['lugar' => 'Urumita' , 'users_id' => 1],
            ['lugar' => 'Villanueva' , 'users_id' => 1],
            ['lugar' => 'Santa Marta' , 'users_id' => 1],
            ['lugar' => 'Algarrobo' , 'users_id' => 1],
            ['lugar' => 'Aracataca' , 'users_id' => 1],
            ['lugar' => 'Ariguaní' , 'users_id' => 1],
            ['lugar' => 'Cerro San Antonio' , 'users_id' => 1],
            ['lugar' => 'Chivolo' , 'users_id' => 1],
            ['lugar' => 'Concordia' , 'users_id' => 1],
            ['lugar' => 'El Banco' , 'users_id' => 1],
            ['lugar' => 'El Piñon' , 'users_id' => 1],
            ['lugar' => 'El Retén' , 'users_id' => 1],
            ['lugar' => 'Fundación' , 'users_id' => 1],
            ['lugar' => 'Guamal' , 'users_id' => 1],
            ['lugar' => 'Nueva Granada' , 'users_id' => 1],
            ['lugar' => 'Pedraza' , 'users_id' => 1],
            ['lugar' => 'Pivijay' , 'users_id' => 1],
            ['lugar' => 'Plato' , 'users_id' => 1],
            ['lugar' => 'Remolino' , 'users_id' => 1],
            ['lugar' => 'Salamina' , 'users_id' => 1],
            ['lugar' => 'San Zenón' , 'users_id' => 1],
            ['lugar' => 'Santa Ana' , 'users_id' => 1],
            ['lugar' => 'Sitionuevo' , 'users_id' => 1],
            ['lugar' => 'Tenerife' , 'users_id' => 1],
            ['lugar' => 'Zapayán' , 'users_id' => 1],
            ['lugar' => 'Zona Bananera' , 'users_id' => 1],
            ['lugar' => 'Villavicencio' , 'users_id' => 1],
            ['lugar' => 'Acacias' , 'users_id' => 1],
            ['lugar' => 'Cabuyaro' , 'users_id' => 1],
            ['lugar' => 'Cubarral' , 'users_id' => 1],
            ['lugar' => 'Cumaral' , 'users_id' => 1],
            ['lugar' => 'El Calvario' , 'users_id' => 1],
            ['lugar' => 'El Castillo' , 'users_id' => 1],
            ['lugar' => 'El Dorado' , 'users_id' => 1],
            ['lugar' => 'Buenaventura' , 'users_id' => 1],
            ['lugar' => 'Granada' , 'users_id' => 1],
            ['lugar' => 'Guamal' , 'users_id' => 1],
            ['lugar' => 'Mapiripán' , 'users_id' => 1],
            ['lugar' => 'Mesetas' , 'users_id' => 1],
            ['lugar' => 'La Macarena' , 'users_id' => 1],
            ['lugar' => 'Uribe' , 'users_id' => 1],
            ['lugar' => 'Lejanías' , 'users_id' => 1],
            ['lugar' => 'Puerto Concordia' , 'users_id' => 1],
            ['lugar' => 'Puerto Gaitán' , 'users_id' => 1],
            ['lugar' => 'Puerto López' , 'users_id' => 1],
            ['lugar' => 'Puerto Lleras' , 'users_id' => 1],
            ['lugar' => 'Puerto Rico' , 'users_id' => 1],
            ['lugar' => 'Restrepo' , 'users_id' => 1],
            ['lugar' => 'Ciénaga' , 'users_id' => 1],
            ['lugar' => 'Ponedera' , 'users_id' => 1],
            ['lugar' => 'San Juanito' , 'users_id' => 1],
            ['lugar' => 'San Martín' , 'users_id' => 1],
            ['lugar' => 'Vista Hermosa' , 'users_id' => 1],
            ['lugar' => 'Pasto' , 'users_id' => 1],
            ['lugar' => 'Albán' , 'users_id' => 1],
            ['lugar' => 'Aldana' , 'users_id' => 1],
            ['lugar' => 'Ancuyá' , 'users_id' => 1],
            ['lugar' => 'Tununguá' , 'users_id' => 1],
            ['lugar' => 'Barbacoas' , 'users_id' => 1],
            ['lugar' => 'Motavita' , 'users_id' => 1],
            ['lugar' => 'San Bernardo del Viento' , 'users_id' => 1],
            ['lugar' => 'Colón' , 'users_id' => 1],
            ['lugar' => 'Consaca' , 'users_id' => 1],
            ['lugar' => 'Contadero' , 'users_id' => 1],
            ['lugar' => 'Córdoba' , 'users_id' => 1],
            ['lugar' => 'Cuaspud' , 'users_id' => 1],
            ['lugar' => 'Cumbal' , 'users_id' => 1],
            ['lugar' => 'Cumbitara' , 'users_id' => 1],
            ['lugar' => 'El Charco' , 'users_id' => 1],
            ['lugar' => 'El Peñol' , 'users_id' => 1],
            ['lugar' => 'El Rosario' , 'users_id' => 1],
            ['lugar' => 'Istmina' , 'users_id' => 1],
            ['lugar' => 'El Tambo' , 'users_id' => 1],
            ['lugar' => 'Funes' , 'users_id' => 1],
            ['lugar' => 'Guachucal' , 'users_id' => 1],
            ['lugar' => 'Guaitarilla' , 'users_id' => 1],
            ['lugar' => 'Gualmatán' , 'users_id' => 1],
            ['lugar' => 'Iles' , 'users_id' => 1],
            ['lugar' => 'Imués' , 'users_id' => 1],
            ['lugar' => 'Ipiales' , 'users_id' => 1],
            ['lugar' => 'La Cruz' , 'users_id' => 1],
            ['lugar' => 'La Florida' , 'users_id' => 1],
            ['lugar' => 'La Llanada' , 'users_id' => 1],
            ['lugar' => 'La Tola' , 'users_id' => 1],
            ['lugar' => 'La Unión' , 'users_id' => 1],
            ['lugar' => 'Leiva' , 'users_id' => 1],
            ['lugar' => 'Linares' , 'users_id' => 1],
            ['lugar' => 'Los Andes' , 'users_id' => 1],
            ['lugar' => 'Magüí' , 'users_id' => 1],
            ['lugar' => 'Mallama' , 'users_id' => 1],
            ['lugar' => 'Mosquera' , 'users_id' => 1],
            ['lugar' => 'Nariño' , 'users_id' => 1],
            ['lugar' => 'Olaya Herrera' , 'users_id' => 1],
            ['lugar' => 'Ospina' , 'users_id' => 1],
            ['lugar' => 'Francisco Pizarro' , 'users_id' => 1],
            ['lugar' => 'Policarpa' , 'users_id' => 1],
            ['lugar' => 'Potosí' , 'users_id' => 1],
            ['lugar' => 'Providencia' , 'users_id' => 1],
            ['lugar' => 'Puerres' , 'users_id' => 1],
            ['lugar' => 'Pupiales' , 'users_id' => 1],
            ['lugar' => 'Ricaurte' , 'users_id' => 1],
            ['lugar' => 'Roberto Payán' , 'users_id' => 1],
            ['lugar' => 'Samaniego' , 'users_id' => 1],
            ['lugar' => 'Sandoná' , 'users_id' => 1],
            ['lugar' => 'San Bernardo' , 'users_id' => 1],
            ['lugar' => 'San Lorenzo' , 'users_id' => 1],
            ['lugar' => 'San Pablo' , 'users_id' => 1],
            ['lugar' => 'Belmira' , 'users_id' => 1],
            ['lugar' => 'Ciénega' , 'users_id' => 1],
            ['lugar' => 'Santa Bárbara' , 'users_id' => 1],
            ['lugar' => 'Sapuyes' , 'users_id' => 1],
            ['lugar' => 'Taminango' , 'users_id' => 1],
            ['lugar' => 'Tangua' , 'users_id' => 1],
            ['lugar' => 'Santacruz' , 'users_id' => 1],
            ['lugar' => 'Túquerres' , 'users_id' => 1],
            ['lugar' => 'Yacuanquer' , 'users_id' => 1],
            ['lugar' => 'Puerto Wilches' , 'users_id' => 1],
            ['lugar' => 'Puerto Parra' , 'users_id' => 1],
            ['lugar' => 'Armenia' , 'users_id' => 1],
            ['lugar' => 'Buenavista' , 'users_id' => 1],
            ['lugar' => 'Circasia' , 'users_id' => 1],
            ['lugar' => 'Córdoba' , 'users_id' => 1],
            ['lugar' => 'Filandia' , 'users_id' => 1],
            ['lugar' => 'La Tebaida' , 'users_id' => 1],
            ['lugar' => 'Montenegro' , 'users_id' => 1],
            ['lugar' => 'Pijao' , 'users_id' => 1],
            ['lugar' => 'Quimbaya' , 'users_id' => 1],
            ['lugar' => 'Salento' , 'users_id' => 1],
            ['lugar' => 'Pereira' , 'users_id' => 1],
            ['lugar' => 'Apía' , 'users_id' => 1],
            ['lugar' => 'Balboa' , 'users_id' => 1],
            ['lugar' => 'Dosquebradas' , 'users_id' => 1],
            ['lugar' => 'Guática' , 'users_id' => 1],
            ['lugar' => 'La Celia' , 'users_id' => 1],
            ['lugar' => 'La Virginia' , 'users_id' => 1],
            ['lugar' => 'Marsella' , 'users_id' => 1],
            ['lugar' => 'Mistrató' , 'users_id' => 1],
            ['lugar' => 'Pueblo Rico' , 'users_id' => 1],
            ['lugar' => 'Quinchía' , 'users_id' => 1],
            ['lugar' => 'Santuario' , 'users_id' => 1],
            ['lugar' => 'Bucaramanga' , 'users_id' => 1],
            ['lugar' => 'Aguada' , 'users_id' => 1],
            ['lugar' => 'Albania' , 'users_id' => 1],
            ['lugar' => 'Aratoca' , 'users_id' => 1],
            ['lugar' => 'Barbosa' , 'users_id' => 1],
            ['lugar' => 'Barichara' , 'users_id' => 1],
            ['lugar' => 'Barrancabermeja' , 'users_id' => 1],
            ['lugar' => 'Betulia' , 'users_id' => 1],
            ['lugar' => 'Bolívar' , 'users_id' => 1],
            ['lugar' => 'Cabrera' , 'users_id' => 1],
            ['lugar' => 'California' , 'users_id' => 1],
            ['lugar' => 'Carcasí' , 'users_id' => 1],
            ['lugar' => 'Cepitá' , 'users_id' => 1],
            ['lugar' => 'Cerrito' , 'users_id' => 1],
            ['lugar' => 'Charalá' , 'users_id' => 1],
            ['lugar' => 'Charta' , 'users_id' => 1],
            ['lugar' => 'Chipatá' , 'users_id' => 1],
            ['lugar' => 'Cimitarra' , 'users_id' => 1],
            ['lugar' => 'Concepción' , 'users_id' => 1],
            ['lugar' => 'Confines' , 'users_id' => 1],
            ['lugar' => 'Contratación' , 'users_id' => 1],
            ['lugar' => 'Coromoro' , 'users_id' => 1],
            ['lugar' => 'Curití' , 'users_id' => 1],
            ['lugar' => 'El Guacamayo' , 'users_id' => 1],
            ['lugar' => 'El Playón' , 'users_id' => 1],
            ['lugar' => 'Encino' , 'users_id' => 1],
            ['lugar' => 'Enciso' , 'users_id' => 1],
            ['lugar' => 'Florián' , 'users_id' => 1],
            ['lugar' => 'Floridablanca' , 'users_id' => 1],
            ['lugar' => 'Galán' , 'users_id' => 1],
            ['lugar' => 'Gambita' , 'users_id' => 1],
            ['lugar' => 'Girón' , 'users_id' => 1],
            ['lugar' => 'Guaca' , 'users_id' => 1],
            ['lugar' => 'Guadalupe' , 'users_id' => 1],
            ['lugar' => 'Guapotá' , 'users_id' => 1],
            ['lugar' => 'Guavatá' , 'users_id' => 1],
            ['lugar' => 'Güepsa' , 'users_id' => 1],
            ['lugar' => 'Jesús María' , 'users_id' => 1],
            ['lugar' => 'Jordán' , 'users_id' => 1],
            ['lugar' => 'La Belleza' , 'users_id' => 1],
            ['lugar' => 'Landázuri' , 'users_id' => 1],
            ['lugar' => 'La Paz' , 'users_id' => 1],
            ['lugar' => 'Lebríja' , 'users_id' => 1],
            ['lugar' => 'Los Santos' , 'users_id' => 1],
            ['lugar' => 'Macaravita' , 'users_id' => 1],
            ['lugar' => 'Málaga' , 'users_id' => 1],
            ['lugar' => 'Matanza' , 'users_id' => 1],
            ['lugar' => 'Mogotes' , 'users_id' => 1],
            ['lugar' => 'Molagavita' , 'users_id' => 1],
            ['lugar' => 'Ocamonte' , 'users_id' => 1],
            ['lugar' => 'Oiba' , 'users_id' => 1],
            ['lugar' => 'Onzaga' , 'users_id' => 1],
            ['lugar' => 'Palmar' , 'users_id' => 1],
            ['lugar' => 'Páramo' , 'users_id' => 1],
            ['lugar' => 'Piedecuesta' , 'users_id' => 1],
            ['lugar' => 'Pinchote' , 'users_id' => 1],
            ['lugar' => 'Puente Nacional' , 'users_id' => 1],
            ['lugar' => 'Rionegro' , 'users_id' => 1],
            ['lugar' => 'San Andrés' , 'users_id' => 1],
            ['lugar' => 'San Gil' , 'users_id' => 1],
            ['lugar' => 'San Joaquín' , 'users_id' => 1],
            ['lugar' => 'San Miguel' , 'users_id' => 1],
            ['lugar' => 'Santa Bárbara' , 'users_id' => 1],
            ['lugar' => 'Simacota' , 'users_id' => 1],
            ['lugar' => 'Socorro' , 'users_id' => 1],
            ['lugar' => 'Suaita' , 'users_id' => 1],
            ['lugar' => 'Sucre' , 'users_id' => 1],
            ['lugar' => 'Suratá' , 'users_id' => 1],
            ['lugar' => 'Tona' , 'users_id' => 1],
            ['lugar' => 'Vélez' , 'users_id' => 1],
            ['lugar' => 'Vetas' , 'users_id' => 1],
            ['lugar' => 'Villanueva' , 'users_id' => 1],
            ['lugar' => 'Zapatoca' , 'users_id' => 1],
            ['lugar' => 'Sincelejo' , 'users_id' => 1],
            ['lugar' => 'Buenavista' , 'users_id' => 1],
            ['lugar' => 'Caimito' , 'users_id' => 1],
            ['lugar' => 'Coloso' , 'users_id' => 1],
            ['lugar' => 'Coveñas' , 'users_id' => 1],
            ['lugar' => 'Chalán' , 'users_id' => 1],
            ['lugar' => 'El Roble' , 'users_id' => 1],
            ['lugar' => 'Galeras' , 'users_id' => 1],
            ['lugar' => 'Guaranda' , 'users_id' => 1],
            ['lugar' => 'La Unión' , 'users_id' => 1],
            ['lugar' => 'Los Palmitos' , 'users_id' => 1],
            ['lugar' => 'Majagual' , 'users_id' => 1],
            ['lugar' => 'Morroa' , 'users_id' => 1],
            ['lugar' => 'Ovejas' , 'users_id' => 1],
            ['lugar' => 'Palmito' , 'users_id' => 1],
            ['lugar' => 'San Benito Abad' , 'users_id' => 1],
            ['lugar' => 'San Marcos' , 'users_id' => 1],
            ['lugar' => 'San Onofre' , 'users_id' => 1],
            ['lugar' => 'San Pedro' , 'users_id' => 1],
            ['lugar' => 'Sucre' , 'users_id' => 1],
            ['lugar' => 'Tolú Viejo' , 'users_id' => 1],
            ['lugar' => 'Alpujarra' , 'users_id' => 1],
            ['lugar' => 'Alvarado' , 'users_id' => 1],
            ['lugar' => 'Ambalema' , 'users_id' => 1],
            ['lugar' => 'Armero' , 'users_id' => 1],
            ['lugar' => 'Ataco' , 'users_id' => 1],
            ['lugar' => 'Cajamarca' , 'users_id' => 1],
            ['lugar' => 'Chaparral' , 'users_id' => 1],
            ['lugar' => 'Coello' , 'users_id' => 1],
            ['lugar' => 'Coyaima' , 'users_id' => 1],
            ['lugar' => 'Cunday' , 'users_id' => 1],
            ['lugar' => 'Dolores' , 'users_id' => 1],
            ['lugar' => 'Espinal' , 'users_id' => 1],
            ['lugar' => 'Falan' , 'users_id' => 1],
            ['lugar' => 'Flandes' , 'users_id' => 1],
            ['lugar' => 'Fresno' , 'users_id' => 1],
            ['lugar' => 'Guamo' , 'users_id' => 1],
            ['lugar' => 'Herveo' , 'users_id' => 1],
            ['lugar' => 'Honda' , 'users_id' => 1],
            ['lugar' => 'Icononzo' , 'users_id' => 1],
            ['lugar' => 'Mariquita' , 'users_id' => 1],
            ['lugar' => 'Melgar' , 'users_id' => 1],
            ['lugar' => 'Murillo' , 'users_id' => 1],
            ['lugar' => 'Natagaima' , 'users_id' => 1],
            ['lugar' => 'Ortega' , 'users_id' => 1],
            ['lugar' => 'Palocabildo' , 'users_id' => 1],
            ['lugar' => 'Piedras' , 'users_id' => 1],
            ['lugar' => 'Planadas' , 'users_id' => 1],
            ['lugar' => 'Prado' , 'users_id' => 1],
            ['lugar' => 'Purificación' , 'users_id' => 1],
            ['lugar' => 'Rio Blanco' , 'users_id' => 1],
            ['lugar' => 'Roncesvalles' , 'users_id' => 1],
            ['lugar' => 'Rovira' , 'users_id' => 1],
            ['lugar' => 'Saldaña' , 'users_id' => 1],
            ['lugar' => 'Santa Isabel' , 'users_id' => 1],
            ['lugar' => 'Venadillo' , 'users_id' => 1],
            ['lugar' => 'Villahermosa' , 'users_id' => 1],
            ['lugar' => 'Villarrica' , 'users_id' => 1],
            ['lugar' => 'Arauquita' , 'users_id' => 1],
            ['lugar' => 'Cravo Norte' , 'users_id' => 1],
            ['lugar' => 'Fortul' , 'users_id' => 1],
            ['lugar' => 'Puerto Rondón' , 'users_id' => 1],
            ['lugar' => 'Saravena' , 'users_id' => 1],
            ['lugar' => 'Tame' , 'users_id' => 1],
            ['lugar' => 'Arauca' , 'users_id' => 1],
            ['lugar' => 'Yopal' , 'users_id' => 1],
            ['lugar' => 'Aguazul' , 'users_id' => 1],
            ['lugar' => 'Chámeza' , 'users_id' => 1],
            ['lugar' => 'Hato Corozal' , 'users_id' => 1],
            ['lugar' => 'La Salina' , 'users_id' => 1],
            ['lugar' => 'Monterrey' , 'users_id' => 1],
            ['lugar' => 'Pore' , 'users_id' => 1],
            ['lugar' => 'Recetor' , 'users_id' => 1],
            ['lugar' => 'Sabanalarga' , 'users_id' => 1],
            ['lugar' => 'Sácama' , 'users_id' => 1],
            ['lugar' => 'Tauramena' , 'users_id' => 1],
            ['lugar' => 'Trinidad' , 'users_id' => 1],
            ['lugar' => 'Villanueva' , 'users_id' => 1],
            ['lugar' => 'Mocoa' , 'users_id' => 1],
            ['lugar' => 'Colón' , 'users_id' => 1],
            ['lugar' => 'Orito' , 'users_id' => 1],
            ['lugar' => 'Puerto Caicedo' , 'users_id' => 1],
            ['lugar' => 'Puerto Guzmán' , 'users_id' => 1],
            ['lugar' => 'Leguízamo' , 'users_id' => 1],
            ['lugar' => 'Sibundoy' , 'users_id' => 1],
            ['lugar' => 'San Francisco' , 'users_id' => 1],
            ['lugar' => 'San Miguel' , 'users_id' => 1],
            ['lugar' => 'Santiago' , 'users_id' => 1],
            ['lugar' => 'Leticia' , 'users_id' => 1],
            ['lugar' => 'El Encanto' , 'users_id' => 1],
            ['lugar' => 'La Chorrera' , 'users_id' => 1],
            ['lugar' => 'La Pedrera' , 'users_id' => 1],
            ['lugar' => 'La Victoria' , 'users_id' => 1],
            ['lugar' => 'Puerto Arica' , 'users_id' => 1],
            ['lugar' => 'Puerto Nariño' , 'users_id' => 1],
            ['lugar' => 'Puerto Santander' , 'users_id' => 1],
            ['lugar' => 'Tarapacá' , 'users_id' => 1],
            ['lugar' => 'Inírida' , 'users_id' => 1],
            ['lugar' => 'Barranco Minas' , 'users_id' => 1],
            ['lugar' => 'Mapiripana' , 'users_id' => 1],
            ['lugar' => 'San Felipe' , 'users_id' => 1],
            ['lugar' => 'Puerto Colombia' , 'users_id' => 1],
            ['lugar' => 'La Guadalupe' , 'users_id' => 1],
            ['lugar' => 'Cacahual' , 'users_id' => 1],
            ['lugar' => 'Pana Pana' , 'users_id' => 1],
            ['lugar' => 'Morichal' , 'users_id' => 1],
            ['lugar' => 'Mitú' , 'users_id' => 1],
            ['lugar' => 'Caruru' , 'users_id' => 1],
            ['lugar' => 'Pacoa' , 'users_id' => 1],
            ['lugar' => 'Taraira' , 'users_id' => 1],
            ['lugar' => 'Papunaua' , 'users_id' => 1],
            ['lugar' => 'Puerto Carreño' , 'users_id' => 1],
            ['lugar' => 'La Primavera' , 'users_id' => 1],
            ['lugar' => 'Santa Rosalía' , 'users_id' => 1],
            ['lugar' => 'Cumaribo' , 'users_id' => 1],
            ['lugar' => 'San José del Fragua' , 'users_id' => 1],
            ['lugar' => 'Barranca de Upía' , 'users_id' => 1],
            ['lugar' => 'Palmas del Socorro' , 'users_id' => 1],
            ['lugar' => 'San Juan de Río Seco' , 'users_id' => 1],
            ['lugar' => 'Juan de Acosta' , 'users_id' => 1],
            ['lugar' => 'Fuente de Oro' , 'users_id' => 1],
            ['lugar' => 'San Luis de Gaceno' , 'users_id' => 1],
            ['lugar' => 'El Litoral del San Juan' , 'users_id' => 1],
            ['lugar' => 'Villa de San Diego de Ubate' , 'users_id' => 1],
            ['lugar' => 'Barranco de Loba' , 'users_id' => 1],
            ['lugar' => 'Togüí' , 'users_id' => 1],
            ['lugar' => 'Santa Rosa del Sur' , 'users_id' => 1],
            ['lugar' => 'El Cantón del San Pablo' , 'users_id' => 1],
            ['lugar' => 'Villa de Leyva' , 'users_id' => 1],
            ['lugar' => 'San Sebastián de Buenavista' , 'users_id' => 1],
            ['lugar' => 'Paz de Río' , 'users_id' => 1],
            ['lugar' => 'Hatillo de Loba' , 'users_id' => 1],
            ['lugar' => 'Sabanas de San Angel' , 'users_id' => 1],
            ['lugar' => 'Calamar' , 'users_id' => 1],
            ['lugar' => 'Río de Oro' , 'users_id' => 1],
            ['lugar' => 'San Pedro de Uraba' , 'users_id' => 1],
            ['lugar' => 'San José del Guaviare' , 'users_id' => 1],
            ['lugar' => 'Santa Rosa de Viterbo' , 'users_id' => 1],
            ['lugar' => 'Santander de Quilichao' , 'users_id' => 1],
            ['lugar' => 'Miraflores' , 'users_id' => 1],
            ['lugar' => 'Santafé de Antioquia' , 'users_id' => 1],
            ['lugar' => 'San Carlos de Guaroa' , 'users_id' => 1],
            ['lugar' => 'Palmar de Varela' , 'users_id' => 1],
            ['lugar' => 'Santa Rosa de Osos' , 'users_id' => 1],
            ['lugar' => 'San Andrés de Cuerquía' , 'users_id' => 1],
            ['lugar' => 'Valle de San Juan' , 'users_id' => 1],
            ['lugar' => 'San Vicente de Chucurí' , 'users_id' => 1],
            ['lugar' => 'San José de Miranda' , 'users_id' => 1],
            ['lugar' => 'Providencia' , 'users_id' => 1],
            ['lugar' => 'Santa Rosa de Cabal' , 'users_id' => 1],
            ['lugar' => 'Guayabal de Siquima' , 'users_id' => 1],
            ['lugar' => 'Belén de Los Andaquies' , 'users_id' => 1],
            ['lugar' => 'Paz de Ariporo' , 'users_id' => 1],
            ['lugar' => 'Santa Helena del Opón' , 'users_id' => 1],
            ['lugar' => 'San Pablo de Borbur' , 'users_id' => 1],
            ['lugar' => 'La Jagua del Pilar' , 'users_id' => 1],
            ['lugar' => 'La Jagua de Ibirico' , 'users_id' => 1],
            ['lugar' => 'San Luis de Sincé' , 'users_id' => 1],
            ['lugar' => 'San Luis de Gaceno' , 'users_id' => 1],
            ['lugar' => 'El Carmen de Bolívar' , 'users_id' => 1],
            ['lugar' => 'El Carmen de Atrato' , 'users_id' => 1],
            ['lugar' => 'San Juan de Betulia' , 'users_id' => 1],
            ['lugar' => 'Pijiño del Carmen' , 'users_id' => 1],
            ['lugar' => 'Vigía del Fuerte' , 'users_id' => 1],
            ['lugar' => 'San Martín de Loba' , 'users_id' => 1],
            ['lugar' => 'Altos del Rosario' , 'users_id' => 1],
            ['lugar' => 'Carmen de Apicala' , 'users_id' => 1],
            ['lugar' => 'San Antonio del Tequendama' , 'users_id' => 1],
            ['lugar' => 'Sabana de Torres' , 'users_id' => 1],
            ['lugar' => 'El Retorno' , 'users_id' => 1],
            ['lugar' => 'San José de Uré' , 'users_id' => 1],
            ['lugar' => 'San Pedro de Cartago' , 'users_id' => 1],
            ['lugar' => 'Campo de La Cruz' , 'users_id' => 1],
            ['lugar' => 'San Juan de Arama' , 'users_id' => 1],
            ['lugar' => 'San José de La Montaña' , 'users_id' => 1],
            ['lugar' => 'Cartagena del Chairá' , 'users_id' => 1],
            ['lugar' => 'San José del Palmar' , 'users_id' => 1],
            ['lugar' => 'Agua de Dios' , 'users_id' => 1],
            ['lugar' => 'San Jacinto del Cauca' , 'users_id' => 1],
            ['lugar' => 'San Agustín' , 'users_id' => 1],
            ['lugar' => 'El Tablón de Gómez' , 'users_id' => 1],
            ['lugar' => 'San Andrés' , 'users_id' => 1],
            ['lugar' => 'San José de Pare' , 'users_id' => 1],
            ['lugar' => 'Valle de Guamez' , 'users_id' => 1],
            ['lugar' => 'San Pablo de Borbur' , 'users_id' => 1],
            ['lugar' => 'Santiago de Tolú' , 'users_id' => 1],
            ['lugar' => 'Bogotá D.C.' , 'users_id' => 1],
            ['lugar' => 'Carmen de Carupa' , 'users_id' => 1],
            ['lugar' => 'Ciénaga de Oro' , 'users_id' => 1],
            ['lugar' => 'San Juan de Urabá' , 'users_id' => 1],
            ['lugar' => 'San Juan del Cesar' , 'users_id' => 1],
            ['lugar' => 'El Carmen de Chucurí' , 'users_id' => 1],
            ['lugar' => 'El Carmen de Viboral' , 'users_id' => 1],
            ['lugar' => 'Belén de Umbría' , 'users_id' => 1],
            ['lugar' => 'Belén de Bajira' , 'users_id' => 1],
            ['lugar' => 'Valle de San José' , 'users_id' => 1],
            ['lugar' => 'San Luis' , 'users_id' => 1],
            ['lugar' => 'San Miguel de Sema' , 'users_id' => 1],
            ['lugar' => 'San Antonio' , 'users_id' => 1],
            ['lugar' => 'San Benito' , 'users_id' => 1],
            ['lugar' => 'Vergara' , 'users_id' => 1],
            ['lugar' => 'San Carlos' , 'users_id' => 1],
            ['lugar' => 'Puerto Alegría' , 'users_id' => 1],
            ['lugar' => 'Hato' , 'users_id' => 1],
            ['lugar' => 'San Jacinto' , 'users_id' => 1],
            ['lugar' => 'San Sebastián' , 'users_id' => 1],
            ['lugar' => 'San Carlos' , 'users_id' => 1],
            ['lugar' => 'Tuta' , 'users_id' => 1],
            ['lugar' => 'Silos' , 'users_id' => 1],
            ['lugar' => 'Cácota' , 'users_id' => 1],
            ['lugar' => 'El Dovio' , 'users_id' => 1],
            ['lugar' => 'Toledo' , 'users_id' => 1],
            ['lugar' => 'Roldanillo' , 'users_id' => 1],
            ['lugar' => 'Mutiscua' , 'users_id' => 1],
            ['lugar' => 'Argelia' , 'users_id' => 1],
            ['lugar' => 'El Zulia' , 'users_id' => 1],
            ['lugar' => 'Salazar' , 'users_id' => 1],
            ['lugar' => 'Sevilla' , 'users_id' => 1],
            ['lugar' => 'Zarzal' , 'users_id' => 1],
            ['lugar' => 'Cucutilla' , 'users_id' => 1],
            ['lugar' => 'El Cerrito' , 'users_id' => 1],
            ['lugar' => 'Cartago' , 'users_id' => 1],
            ['lugar' => 'Caicedonia' , 'users_id' => 1],
            ['lugar' => 'Puerto Santander' , 'users_id' => 1],
            ['lugar' => 'Gramalote' , 'users_id' => 1],
            ['lugar' => 'El Cairo' , 'users_id' => 1],
            ['lugar' => 'El Tarra' , 'users_id' => 1],
            ['lugar' => 'La Unión' , 'users_id' => 1],
            ['lugar' => 'Restrepo' , 'users_id' => 1],
            ['lugar' => 'Teorama' , 'users_id' => 1],
            ['lugar' => 'Dagua' , 'users_id' => 1],
            ['lugar' => 'Arboledas' , 'users_id' => 1],
            ['lugar' => 'Guacarí' , 'users_id' => 1],
            ['lugar' => 'Lourdes' , 'users_id' => 1],
            ['lugar' => 'Ansermanuevo' , 'users_id' => 1],
            ['lugar' => 'Bochalema' , 'users_id' => 1],
            ['lugar' => 'Bugalagrande' , 'users_id' => 1],
            ['lugar' => 'Convención' , 'users_id' => 1],
            ['lugar' => 'Hacarí' , 'users_id' => 1],
            ['lugar' => 'La Victoria' , 'users_id' => 1],
            ['lugar' => 'Herrán' , 'users_id' => 1],
            ['lugar' => 'Ginebra' , 'users_id' => 1],
            ['lugar' => 'Yumbo' , 'users_id' => 1],
            ['lugar' => 'Obando' , 'users_id' => 1],
            ['lugar' => 'Tibú' , 'users_id' => 1],
            ['lugar' => 'San Cayetano' , 'users_id' => 1],
            ['lugar' => 'San Calixto' , 'users_id' => 1],
            ['lugar' => 'Bolívar' , 'users_id' => 1],
            ['lugar' => 'La Playa' , 'users_id' => 1],
            ['lugar' => 'Cali' , 'users_id' => 1],
            ['lugar' => 'San Pedro' , 'users_id' => 1],
            ['lugar' => 'Guadalajara de Buga' , 'users_id' => 1],
            ['lugar' => 'Chinácota' , 'users_id' => 1],
            ['lugar' => 'Ragonvalia' , 'users_id' => 1],
            ['lugar' => 'La Esperanza' , 'users_id' => 1],
            ['lugar' => 'Villa del Rosario' , 'users_id' => 1],
            ['lugar' => 'Chitagá' , 'users_id' => 1],
            ['lugar' => 'Calima' , 'users_id' => 1],
            ['lugar' => 'Sardinata' , 'users_id' => 1],
            ['lugar' => 'Andalucía' , 'users_id' => 1],
            ['lugar' => 'Pradera' , 'users_id' => 1],
            ['lugar' => 'Abrego' , 'users_id' => 1],
            ['lugar' => 'Los Patios' , 'users_id' => 1],
            ['lugar' => 'Ocaña' , 'users_id' => 1],
            ['lugar' => 'Bucarasica' , 'users_id' => 1],
            ['lugar' => 'Yotoco' , 'users_id' => 1],
            ['lugar' => 'Palmira' , 'users_id' => 1],
            ['lugar' => 'Riofrío' , 'users_id' => 1],
            ['lugar' => 'Santiago' , 'users_id' => 1],
            ['lugar' => 'Alcalá' , 'users_id' => 1],
            ['lugar' => 'Versalles' , 'users_id' => 1],
            ['lugar' => 'Labateca' , 'users_id' => 1],
            ['lugar' => 'Cachirá' , 'users_id' => 1],
            ['lugar' => 'Villa Caro' , 'users_id' => 1],
            ['lugar' => 'Durania' , 'users_id' => 1],
            ['lugar' => 'El Águila' , 'users_id' => 1],
            ['lugar' => 'Toro' , 'users_id' => 1],
            ['lugar' => 'Candelaria' , 'users_id' => 1],
            ['lugar' => 'La Cumbre' , 'users_id' => 1],
            ['lugar' => 'Ulloa' , 'users_id' => 1],
            ['lugar' => 'Trujillo' , 'users_id' => 1],
            ['lugar' => 'Vijes' , 'users_id' => 1],
                       
        ]);
    }
}
