<?php

use Illuminate\Database\Seeder;
use App\Models\Municipio;
use Illuminate\Support\Facades\DB;

class MunicipioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('municipio')->truncate();

        Municipio::insert([
            ['departamento_id' => '5',    'nombre' => 'Medellín', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Abejorral', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Abriaquí', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Alejandría', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Amagá', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Amalfi', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Andes', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Angelópolis', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Angostura', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Anorí', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Chimá', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Anza', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Apartadó', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Arboletes', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Argelia', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Armenia', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Barbosa', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Bello', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Betania', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Betulia', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Ciudad Bolívar', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Briceño', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Buriticá', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Cáceres', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Caicedo', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Caldas', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Campamento', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Cañasgordas', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Caracolí', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Caramanta', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Carepa', 'users_id' => 1],
            ['departamento_id' => '70',    'nombre' => 'Sampués', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Carolina', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Caucasia', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Chigorodó', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Cisneros', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Cocorná', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Concepción', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Concordia', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Copacabana', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Dabeiba', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Don Matías', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Ebéjico', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'El Bagre', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Entrerrios', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Envigado', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Fredonia', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Giraldo', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Girardota', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Gómez Plata', 'users_id' => 1],
            ['departamento_id' => '85',    'nombre' => 'Nunchía', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Guadalupe', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Guarne', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Guatapé', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Heliconia', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Hispania', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Itagui', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Ituango', 'users_id' => 1],
            ['departamento_id' => '54',    'nombre' => 'Pamplona', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Jericó', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'La Ceja', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'La Estrella', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'La Pintada', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'La Unión', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Liborina', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Maceo', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Marinilla', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Montebello', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Murindó', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Mutatá', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Nariño', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Necoclí', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Nechí', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Olaya', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Peñol', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Peque', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Pueblorrico', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Puerto Berrío', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Puerto Nare', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Puerto Triunfo', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Remedios', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Retiro', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Rionegro', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Sabanalarga', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Sabaneta', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Salgar', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Albán', 'users_id' => 1],
            ['departamento_id' => '97',    'nombre' => 'Yavaraté', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'San Francisco', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'San Jerónimo', 'users_id' => 1],
            ['departamento_id' => '23',    'nombre' => 'Montelíbano', 'users_id' => 1],
            ['departamento_id' => '86',    'nombre' => 'Puerto Asís', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'San Luis', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'San Pedro', 'users_id' => 1],
            ['departamento_id' => '70',    'nombre' => 'Corozal', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'San Rafael', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'San Roque', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'San Vicente', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Santa Bárbara', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'Buesaco', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Santo Domingo', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'El Santuario', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Segovia', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Sopetrán', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Támesis', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Tarazá', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Tarso', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Titiribí', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Toledo', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Turbo', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Uramita', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Urrao', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Valdivia', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Valparaíso', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Vegachí', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Venecia', 'users_id' => 1],
            ['departamento_id' => '85',    'nombre' => 'Maní', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Yalí', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Yarumal', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Yolombó', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Yondó', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Zaragoza', 'users_id' => 1],
            ['departamento_id' => '8',    'nombre' => 'Barranquilla', 'users_id' => 1],
            ['departamento_id' => '8',    'nombre' => 'Baranoa', 'users_id' => 1],
            ['departamento_id' => '13',    'nombre' => 'El Peñón', 'users_id' => 1],
            ['departamento_id' => '8',    'nombre' => 'Candelaria', 'users_id' => 1],
            ['departamento_id' => '8',    'nombre' => 'Galapa', 'users_id' => 1],
            ['departamento_id' => '76',    'nombre' => 'Tuluá', 'users_id' => 1],
            ['departamento_id' => '73',    'nombre' => 'Casabianca', 'users_id' => 1],
            ['departamento_id' => '8',    'nombre' => 'Luruaco', 'users_id' => 1],
            ['departamento_id' => '8',    'nombre' => 'Malambo', 'users_id' => 1],
            ['departamento_id' => '8',    'nombre' => 'Manatí', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Anolaima', 'users_id' => 1],
            ['departamento_id' => '8',    'nombre' => 'Piojó', 'users_id' => 1],
            ['departamento_id' => '8',    'nombre' => 'Polonuevo', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Chía', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'San Andrés de Tumaco', 'users_id' => 1],
            ['departamento_id' => '8',    'nombre' => 'Sabanagrande', 'users_id' => 1],
            ['departamento_id' => '8',    'nombre' => 'Sabanalarga', 'users_id' => 1],
            ['departamento_id' => '8',    'nombre' => 'Santa Lucía', 'users_id' => 1],
            ['departamento_id' => '8',    'nombre' => 'Santo Tomás', 'users_id' => 1],
            ['departamento_id' => '8',    'nombre' => 'Soledad', 'users_id' => 1],
            ['departamento_id' => '8',    'nombre' => 'Suan', 'users_id' => 1],
            ['departamento_id' => '8',    'nombre' => 'Tubará', 'users_id' => 1],
            ['departamento_id' => '8',    'nombre' => 'Usiacurí', 'users_id' => 1],
            ['departamento_id' => '18',    'nombre' => 'Milán', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Capitanejo', 'users_id' => 1],
            ['departamento_id' => '13',    'nombre' => 'Achí', 'users_id' => 1],
            ['departamento_id' => '73',    'nombre' => 'Anzoátegui', 'users_id' => 1],
            ['departamento_id' => '13',    'nombre' => 'Arenal', 'users_id' => 1],
            ['departamento_id' => '13',    'nombre' => 'Arjona', 'users_id' => 1],
            ['departamento_id' => '13',    'nombre' => 'Arroyohondo', 'users_id' => 1],
            ['departamento_id' => '76',    'nombre' => 'Florida', 'users_id' => 1],
            ['departamento_id' => '13',    'nombre' => 'Calamar', 'users_id' => 1],
            ['departamento_id' => '13',    'nombre' => 'Cantagallo', 'users_id' => 1],
            ['departamento_id' => '13',    'nombre' => 'Cicuco', 'users_id' => 1],
            ['departamento_id' => '13',    'nombre' => 'Córdoba', 'users_id' => 1],
            ['departamento_id' => '13',    'nombre' => 'Clemencia', 'users_id' => 1],
            ['departamento_id' => '8',    'nombre' => 'Repelón', 'users_id' => 1],
            ['departamento_id' => '13',    'nombre' => 'El Guamo', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Frontino', 'users_id' => 1],
            ['departamento_id' => '13',    'nombre' => 'Magangué', 'users_id' => 1],
            ['departamento_id' => '13',    'nombre' => 'Mahates', 'users_id' => 1],
            ['departamento_id' => '13',    'nombre' => 'Margarita', 'users_id' => 1],
            ['departamento_id' => '13',    'nombre' => 'Montecristo', 'users_id' => 1],
            ['departamento_id' => '13',    'nombre' => 'Mompós', 'users_id' => 1],
            ['departamento_id' => '13',    'nombre' => 'Morales', 'users_id' => 1],
            ['departamento_id' => '13',    'nombre' => 'Norosí', 'users_id' => 1],
            ['departamento_id' => '13',    'nombre' => 'Pinillos', 'users_id' => 1],
            ['departamento_id' => '13',    'nombre' => 'Regidor', 'users_id' => 1],
            ['departamento_id' => '13',    'nombre' => 'Río Viejo', 'users_id' => 1],
            ['departamento_id' => '13',    'nombre' => 'San Estanislao', 'users_id' => 1],
            ['departamento_id' => '13',    'nombre' => 'San Fernando', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'El Peñón', 'users_id' => 1],
            ['departamento_id' => '54',    'nombre' => 'Pamplonita', 'users_id' => 1],
            ['departamento_id' => '13',    'nombre' => 'San Juan Nepomuceno', 'users_id' => 1],
            ['departamento_id' => '91',    'nombre' => 'Miriti Paraná', 'users_id' => 1],
            ['departamento_id' => '85',    'nombre' => 'Támara', 'users_id' => 1],
            ['departamento_id' => '13',    'nombre' => 'Santa Catalina', 'users_id' => 1],
            ['departamento_id' => '13',    'nombre' => 'Santa Rosa', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Tibasosa', 'users_id' => 1],
            ['departamento_id' => '13',    'nombre' => 'Simití', 'users_id' => 1],
            ['departamento_id' => '13',    'nombre' => 'Soplaviento', 'users_id' => 1],
            ['departamento_id' => '13',    'nombre' => 'Talaigua Nuevo', 'users_id' => 1],
            ['departamento_id' => '13',    'nombre' => 'Tiquisio', 'users_id' => 1],
            ['departamento_id' => '13',    'nombre' => 'Turbaco', 'users_id' => 1],
            ['departamento_id' => '13',    'nombre' => 'Turbaná', 'users_id' => 1],
            ['departamento_id' => '13',    'nombre' => 'Villanueva', 'users_id' => 1],
            ['departamento_id' => '19',    'nombre' => 'Páez', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Tunja', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Almeida', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Aquitania', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Arcabuco', 'users_id' => 1],
            ['departamento_id' => '73',    'nombre' => 'Ibagué', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Berbeo', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Betéitiva', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Boavita', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Boyacá', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Briceño', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Buena Vista', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Busbanzá', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Caldas', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Campohermoso', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Cerinza', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Chinavita', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Chiquinquirá', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Chiscas', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Chita', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Chitaraque', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Chivatá', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Cómbita', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Coper', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Corrales', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Covarachía', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Cubará', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Cucaita', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Cuítiva', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Chíquiza', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Chivor', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Duitama', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'El Cocuy', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'El Espino', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Firavitoba', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Floresta', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Gachantivá', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Gameza', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Garagoa', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Guacamayas', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Guateque', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Guayatá', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Güicán', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Iza', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Jenesano', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Jericó', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Labranzagrande', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'La Capilla', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'La Victoria', 'users_id' => 1],
            ['departamento_id' => '8',    'nombre' => 'Puerto Colombia', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'Belén', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Macanal', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Maripí', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Miraflores', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Mongua', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Monguí', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Moniquirá', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Muzo', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Nobsa', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Nuevo Colón', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Oicatá', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Otanche', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Pachavita', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Páez', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Paipa', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Pajarito', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Panqueba', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Pauna', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Paya', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Sopó', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Pesca', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Pisba', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Puerto Boyacá', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Quípama', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Ramiriquí', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Ráquira', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Rondón', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Saboyá', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Sáchica', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Samacá', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'San Eduardo', 'users_id' => 1],
            ['departamento_id' => '27',    'nombre' => 'Carmen del Darien', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Gama', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'San Mateo', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Sasaima', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'Chachagüí', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Santana', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Santa María', 'users_id' => 1],
            ['departamento_id' => '54',    'nombre' => 'Cúcuta', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Santa Sofía', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Sativanorte', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Sativasur', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Siachoque', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Soatá', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Socotá', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Socha', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Sogamoso', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Somondoco', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Sora', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Sotaquirá', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Soracá', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Susacón', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Sutamarchán', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Sutatenza', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Tasco', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Tenza', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Tibaná', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Tinjacá', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Tipacoque', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Toca', 'users_id' => 1],
            ['departamento_id' => '13',    'nombre' => 'Cartagena', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Tópaga', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Tota', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Turmequé', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Granada', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Tutazá', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Umbita', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Ventaquemada', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Viracachá', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Zetaquira', 'users_id' => 1],
            ['departamento_id' => '17',    'nombre' => 'Manizales', 'users_id' => 1],
            ['departamento_id' => '17',    'nombre' => 'Aguadas', 'users_id' => 1],
            ['departamento_id' => '17',    'nombre' => 'Anserma', 'users_id' => 1],
            ['departamento_id' => '17',    'nombre' => 'Aranzazu', 'users_id' => 1],
            ['departamento_id' => '17',    'nombre' => 'Belalcázar', 'users_id' => 1],
            ['departamento_id' => '17',    'nombre' => 'Chinchiná', 'users_id' => 1],
            ['departamento_id' => '17',    'nombre' => 'Filadelfia', 'users_id' => 1],
            ['departamento_id' => '17',    'nombre' => 'La Dorada', 'users_id' => 1],
            ['departamento_id' => '17',    'nombre' => 'La Merced', 'users_id' => 1],
            ['departamento_id' => '17',    'nombre' => 'Manzanares', 'users_id' => 1],
            ['departamento_id' => '17',    'nombre' => 'Marmato', 'users_id' => 1],
            ['departamento_id' => '17',    'nombre' => 'Marulanda', 'users_id' => 1],
            ['departamento_id' => '17',    'nombre' => 'Neira', 'users_id' => 1],
            ['departamento_id' => '17',    'nombre' => 'Norcasia', 'users_id' => 1],
            ['departamento_id' => '17',    'nombre' => 'Pácora', 'users_id' => 1],
            ['departamento_id' => '17',    'nombre' => 'Palestina', 'users_id' => 1],
            ['departamento_id' => '17',    'nombre' => 'Pensilvania', 'users_id' => 1],
            ['departamento_id' => '17',    'nombre' => 'Riosucio', 'users_id' => 1],
            ['departamento_id' => '17',    'nombre' => 'Risaralda', 'users_id' => 1],
            ['departamento_id' => '17',    'nombre' => 'Salamina', 'users_id' => 1],
            ['departamento_id' => '17',    'nombre' => 'Samaná', 'users_id' => 1],
            ['departamento_id' => '17',    'nombre' => 'San José', 'users_id' => 1],
            ['departamento_id' => '17',    'nombre' => 'Supía', 'users_id' => 1],
            ['departamento_id' => '17',    'nombre' => 'Victoria', 'users_id' => 1],
            ['departamento_id' => '17',    'nombre' => 'Villamaría', 'users_id' => 1],
            ['departamento_id' => '17',    'nombre' => 'Viterbo', 'users_id' => 1],
            ['departamento_id' => '18',    'nombre' => 'Florencia', 'users_id' => 1],
            ['departamento_id' => '18',    'nombre' => 'Albania', 'users_id' => 1],
            ['departamento_id' => '47',    'nombre' => 'Santa Bárbara de Pinto', 'users_id' => 1],
            ['departamento_id' => '13',    'nombre' => 'María la Baja', 'users_id' => 1],
            ['departamento_id' => '18',    'nombre' => 'Curillo', 'users_id' => 1],
            ['departamento_id' => '18',    'nombre' => 'El Doncello', 'users_id' => 1],
            ['departamento_id' => '18',    'nombre' => 'El Paujil', 'users_id' => 1],
            ['departamento_id' => '18',    'nombre' => 'Morelia', 'users_id' => 1],
            ['departamento_id' => '18',    'nombre' => 'Puerto Rico', 'users_id' => 1],
            ['departamento_id' => '18',    'nombre' => 'La Montañita', 'users_id' => 1],
            ['departamento_id' => '18',    'nombre' => 'San Vicente del Caguán', 'users_id' => 1],
            ['departamento_id' => '18',    'nombre' => 'Solano', 'users_id' => 1],
            ['departamento_id' => '18',    'nombre' => 'Solita', 'users_id' => 1],
            ['departamento_id' => '18',    'nombre' => 'Valparaíso', 'users_id' => 1],
            ['departamento_id' => '19',    'nombre' => 'Popayán', 'users_id' => 1],
            ['departamento_id' => '19',    'nombre' => 'Almaguer', 'users_id' => 1],
            ['departamento_id' => '19',    'nombre' => 'Argelia', 'users_id' => 1],
            ['departamento_id' => '19',    'nombre' => 'Balboa', 'users_id' => 1],
            ['departamento_id' => '19',    'nombre' => 'Bolívar', 'users_id' => 1],
            ['departamento_id' => '19',    'nombre' => 'Buenos Aires', 'users_id' => 1],
            ['departamento_id' => '19',    'nombre' => 'Cajibío', 'users_id' => 1],
            ['departamento_id' => '19',    'nombre' => 'Caldono', 'users_id' => 1],
            ['departamento_id' => '19',    'nombre' => 'Caloto', 'users_id' => 1],
            ['departamento_id' => '19',    'nombre' => 'Corinto', 'users_id' => 1],
            ['departamento_id' => '19',    'nombre' => 'El Tambo', 'users_id' => 1],
            ['departamento_id' => '19',    'nombre' => 'Florencia', 'users_id' => 1],
            ['departamento_id' => '19',    'nombre' => 'Guachené', 'users_id' => 1],
            ['departamento_id' => '19',    'nombre' => 'Guapi', 'users_id' => 1],
            ['departamento_id' => '19',    'nombre' => 'Inzá', 'users_id' => 1],
            ['departamento_id' => '19',    'nombre' => 'Jambaló', 'users_id' => 1],
            ['departamento_id' => '19',    'nombre' => 'La Sierra', 'users_id' => 1],
            ['departamento_id' => '19',    'nombre' => 'La Vega', 'users_id' => 1],
            ['departamento_id' => '19',    'nombre' => 'López', 'users_id' => 1],
            ['departamento_id' => '19',    'nombre' => 'Mercaderes', 'users_id' => 1],
            ['departamento_id' => '19',    'nombre' => 'Miranda', 'users_id' => 1],
            ['departamento_id' => '19',    'nombre' => 'Morales', 'users_id' => 1],
            ['departamento_id' => '19',    'nombre' => 'Padilla', 'users_id' => 1],
            ['departamento_id' => '19',    'nombre' => 'Patía', 'users_id' => 1],
            ['departamento_id' => '19',    'nombre' => 'Piamonte', 'users_id' => 1],
            ['departamento_id' => '19',    'nombre' => 'Piendamó', 'users_id' => 1],
            ['departamento_id' => '19',    'nombre' => 'Puerto Tejada', 'users_id' => 1],
            ['departamento_id' => '19',    'nombre' => 'Puracé', 'users_id' => 1],
            ['departamento_id' => '19',    'nombre' => 'Rosas', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'El Peñón', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Jardín', 'users_id' => 1],
            ['departamento_id' => '19',    'nombre' => 'Santa Rosa', 'users_id' => 1],
            ['departamento_id' => '19',    'nombre' => 'Silvia', 'users_id' => 1],
            ['departamento_id' => '19',    'nombre' => 'Sotara', 'users_id' => 1],
            ['departamento_id' => '19',    'nombre' => 'Suárez', 'users_id' => 1],
            ['departamento_id' => '19',    'nombre' => 'Sucre', 'users_id' => 1],
            ['departamento_id' => '19',    'nombre' => 'Timbío', 'users_id' => 1],
            ['departamento_id' => '19',    'nombre' => 'Timbiquí', 'users_id' => 1],
            ['departamento_id' => '19',    'nombre' => 'Toribio', 'users_id' => 1],
            ['departamento_id' => '19',    'nombre' => 'Totoró', 'users_id' => 1],
            ['departamento_id' => '19',    'nombre' => 'Villa Rica', 'users_id' => 1],
            ['departamento_id' => '20',    'nombre' => 'Valledupar', 'users_id' => 1],
            ['departamento_id' => '20',    'nombre' => 'Aguachica', 'users_id' => 1],
            ['departamento_id' => '20',    'nombre' => 'Agustín Codazzi', 'users_id' => 1],
            ['departamento_id' => '20',    'nombre' => 'Astrea', 'users_id' => 1],
            ['departamento_id' => '20',    'nombre' => 'Becerril', 'users_id' => 1],
            ['departamento_id' => '20',    'nombre' => 'Bosconia', 'users_id' => 1],
            ['departamento_id' => '20',    'nombre' => 'Chimichagua', 'users_id' => 1],
            ['departamento_id' => '20',    'nombre' => 'Chiriguaná', 'users_id' => 1],
            ['departamento_id' => '20',    'nombre' => 'Curumaní', 'users_id' => 1],
            ['departamento_id' => '20',    'nombre' => 'El Copey', 'users_id' => 1],
            ['departamento_id' => '20',    'nombre' => 'El Paso', 'users_id' => 1],
            ['departamento_id' => '20',    'nombre' => 'Gamarra', 'users_id' => 1],
            ['departamento_id' => '20',    'nombre' => 'González', 'users_id' => 1],
            ['departamento_id' => '20',    'nombre' => 'La Gloria', 'users_id' => 1],
            ['departamento_id' => '76',    'nombre' => 'Jamundí', 'users_id' => 1],
            ['departamento_id' => '20',    'nombre' => 'Manaure', 'users_id' => 1],
            ['departamento_id' => '20',    'nombre' => 'Pailitas', 'users_id' => 1],
            ['departamento_id' => '20',    'nombre' => 'Pelaya', 'users_id' => 1],
            ['departamento_id' => '20',    'nombre' => 'Pueblo Bello', 'users_id' => 1],
            ['departamento_id' => '27',    'nombre' => 'Tadó', 'users_id' => 1],
            ['departamento_id' => '20',    'nombre' => 'La Paz', 'users_id' => 1],
            ['departamento_id' => '20',    'nombre' => 'San Alberto', 'users_id' => 1],
            ['departamento_id' => '20',    'nombre' => 'San Diego', 'users_id' => 1],
            ['departamento_id' => '20',    'nombre' => 'San Martín', 'users_id' => 1],
            ['departamento_id' => '20',    'nombre' => 'Tamalameque', 'users_id' => 1],
            ['departamento_id' => '23',    'nombre' => 'Montería', 'users_id' => 1],
            ['departamento_id' => '23',    'nombre' => 'Ayapel', 'users_id' => 1],
            ['departamento_id' => '23',    'nombre' => 'Buenavista', 'users_id' => 1],
            ['departamento_id' => '23',    'nombre' => 'Canalete', 'users_id' => 1],
            ['departamento_id' => '23',    'nombre' => 'Cereté', 'users_id' => 1],
            ['departamento_id' => '23',    'nombre' => 'Chimá', 'users_id' => 1],
            ['departamento_id' => '23',    'nombre' => 'Chinú', 'users_id' => 1],
            ['departamento_id' => '85',    'nombre' => 'Orocué', 'users_id' => 1],
            ['departamento_id' => '23',    'nombre' => 'Cotorra', 'users_id' => 1],
            ['departamento_id' => '73',    'nombre' => 'Líbano', 'users_id' => 1],
            ['departamento_id' => '23',    'nombre' => 'Lorica', 'users_id' => 1],
            ['departamento_id' => '23',    'nombre' => 'Los Córdobas', 'users_id' => 1],
            ['departamento_id' => '23',    'nombre' => 'Momil', 'users_id' => 1],
            ['departamento_id' => '23',    'nombre' => 'Moñitos', 'users_id' => 1],
            ['departamento_id' => '23',    'nombre' => 'Planeta Rica', 'users_id' => 1],
            ['departamento_id' => '23',    'nombre' => 'Pueblo Nuevo', 'users_id' => 1],
            ['departamento_id' => '23',    'nombre' => 'Puerto Escondido', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Yacopí', 'users_id' => 1],
            ['departamento_id' => '23',    'nombre' => 'Purísima', 'users_id' => 1],
            ['departamento_id' => '23',    'nombre' => 'Sahagún', 'users_id' => 1],
            ['departamento_id' => '23',    'nombre' => 'San Andrés Sotavento', 'users_id' => 1],
            ['departamento_id' => '23',    'nombre' => 'San Antero', 'users_id' => 1],
            ['departamento_id' => '63',    'nombre' => 'Calarcá', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Sonsón', 'users_id' => 1],
            ['departamento_id' => '54',    'nombre' => 'El Carmen', 'users_id' => 1],
            ['departamento_id' => '23',    'nombre' => 'San Pelayo', 'users_id' => 1],
            ['departamento_id' => '23',    'nombre' => 'Tierralta', 'users_id' => 1],
            ['departamento_id' => '23',    'nombre' => 'Tuchín', 'users_id' => 1],
            ['departamento_id' => '23',    'nombre' => 'Valencia', 'users_id' => 1],
            ['departamento_id' => '73',    'nombre' => 'Lérida', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Anapoima', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Arbeláez', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Beltrán', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Bituima', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Bojacá', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Cabrera', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Cachipay', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Cajicá', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Caparrapí', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Caqueza', 'users_id' => 1],
            ['departamento_id' => '23',    'nombre' => 'La Apartada', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Chaguaní', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Chipaque', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Choachí', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Chocontá', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Cogua', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Cota', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Cucunubá', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'El Colegio', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'El Rosal', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Fomeque', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Fosca', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Funza', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Fúquene', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Gachala', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Gachancipá', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Gachetá', 'users_id' => 1],
            ['departamento_id' => '13',    'nombre' => 'San Cristóbal', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Girardot', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Granada', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Guachetá', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Guaduas', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Guasca', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Guataquí', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Guatavita', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Fusagasugá', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Guayabetal', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Gutiérrez', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Jerusalén', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Junín', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'La Calera', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'La Mesa', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'La Palma', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'La Peña', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'La Vega', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Lenguazaque', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Macheta', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Madrid', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Manta', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Medina', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Mosquera', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Nariño', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Nemocón', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Nilo', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Nimaima', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Nocaima', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Venecia', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Pacho', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Paime', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Pandi', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Paratebueno', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Pasca', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Puerto Salgar', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Pulí', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Quebradanegra', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Quetame', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Quipile', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Apulo', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Ricaurte', 'users_id' => 1],
            ['departamento_id' => '13',    'nombre' => 'Zambrano', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'San Bernardo', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'San Cayetano', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'San Francisco', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'La Uvita', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Zipaquirá', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Sesquilé', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Sibaté', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Silvania', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Simijaca', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Soacha', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Subachoque', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Suesca', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Supatá', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Susa', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Sutatausa', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Tabio', 'users_id' => 1],
            ['departamento_id' => '63',    'nombre' => 'Génova', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Tausa', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Tena', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Tenjo', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Tibacuy', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Tibirita', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Tocaima', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Tocancipá', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Topaipí', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Ubalá', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Ubaque', 'users_id' => 1],
            ['departamento_id' => '73',    'nombre' => 'Suárez', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Une', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Útica', 'users_id' => 1],
            ['departamento_id' => '50',    'nombre' => 'Castilla la Nueva', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Vianí', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Villagómez', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Villapinzón', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Villeta', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Viotá', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Zipacón', 'users_id' => 1],
            ['departamento_id' => '27',    'nombre' => 'Quibdó', 'users_id' => 1],
            ['departamento_id' => '27',    'nombre' => 'Acandí', 'users_id' => 1],
            ['departamento_id' => '27',    'nombre' => 'Alto Baudo', 'users_id' => 1],
            ['departamento_id' => '27',    'nombre' => 'Atrato', 'users_id' => 1],
            ['departamento_id' => '27',    'nombre' => 'Bagadó', 'users_id' => 1],
            ['departamento_id' => '27',    'nombre' => 'Bahía Solano', 'users_id' => 1],
            ['departamento_id' => '27',    'nombre' => 'Bajo Baudó', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Belén', 'users_id' => 1],
            ['departamento_id' => '27',    'nombre' => 'Bojaya', 'users_id' => 1],
            ['departamento_id' => '27',    'nombre' => 'Unión Panamericana', 'users_id' => 1],
            ['departamento_id' => '47',    'nombre' => 'Pueblo Viejo', 'users_id' => 1],
            ['departamento_id' => '27',    'nombre' => 'Cértegui', 'users_id' => 1],
            ['departamento_id' => '27',    'nombre' => 'Condoto', 'users_id' => 1],
            ['departamento_id' => '86',    'nombre' => 'Villagarzón', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Facatativá', 'users_id' => 1],
            ['departamento_id' => '27',    'nombre' => 'Juradó', 'users_id' => 1],
            ['departamento_id' => '27',    'nombre' => 'Lloró', 'users_id' => 1],
            ['departamento_id' => '27',    'nombre' => 'Medio Atrato', 'users_id' => 1],
            ['departamento_id' => '27',    'nombre' => 'Medio Baudó', 'users_id' => 1],
            ['departamento_id' => '27',    'nombre' => 'Medio San Juan', 'users_id' => 1],
            ['departamento_id' => '27',    'nombre' => 'Nóvita', 'users_id' => 1],
            ['departamento_id' => '27',    'nombre' => 'Nuquí', 'users_id' => 1],
            ['departamento_id' => '27',    'nombre' => 'Río Iro', 'users_id' => 1],
            ['departamento_id' => '27',    'nombre' => 'Río Quito', 'users_id' => 1],
            ['departamento_id' => '27',    'nombre' => 'Riosucio', 'users_id' => 1],
            ['departamento_id' => '23',    'nombre' => 'Puerto Libertador', 'users_id' => 1],
            ['departamento_id' => '27',    'nombre' => 'Sipí', 'users_id' => 1],
            ['departamento_id' => '27',    'nombre' => 'Unguía', 'users_id' => 1],
            ['departamento_id' => '41',    'nombre' => 'Neiva', 'users_id' => 1],
            ['departamento_id' => '41',    'nombre' => 'Acevedo', 'users_id' => 1],
            ['departamento_id' => '41',    'nombre' => 'Agrado', 'users_id' => 1],
            ['departamento_id' => '41',    'nombre' => 'Aipe', 'users_id' => 1],
            ['departamento_id' => '41',    'nombre' => 'Algeciras', 'users_id' => 1],
            ['departamento_id' => '41',    'nombre' => 'Altamira', 'users_id' => 1],
            ['departamento_id' => '41',    'nombre' => 'Baraya', 'users_id' => 1],
            ['departamento_id' => '41',    'nombre' => 'Campoalegre', 'users_id' => 1],
            ['departamento_id' => '41',    'nombre' => 'Colombia', 'users_id' => 1],
            ['departamento_id' => '41',    'nombre' => 'Elías', 'users_id' => 1],
            ['departamento_id' => '41',    'nombre' => 'Garzón', 'users_id' => 1],
            ['departamento_id' => '41',    'nombre' => 'Gigante', 'users_id' => 1],
            ['departamento_id' => '41',    'nombre' => 'Guadalupe', 'users_id' => 1],
            ['departamento_id' => '41',    'nombre' => 'Hobo', 'users_id' => 1],
            ['departamento_id' => '41',    'nombre' => 'Iquira', 'users_id' => 1],
            ['departamento_id' => '41',    'nombre' => 'Isnos', 'users_id' => 1],
            ['departamento_id' => '41',    'nombre' => 'La Argentina', 'users_id' => 1],
            ['departamento_id' => '41',    'nombre' => 'La Plata', 'users_id' => 1],
            ['departamento_id' => '17',    'nombre' => 'Marquetalia', 'users_id' => 1],
            ['departamento_id' => '41',    'nombre' => 'Nátaga', 'users_id' => 1],
            ['departamento_id' => '41',    'nombre' => 'Oporapa', 'users_id' => 1],
            ['departamento_id' => '41',    'nombre' => 'Paicol', 'users_id' => 1],
            ['departamento_id' => '41',    'nombre' => 'Palermo', 'users_id' => 1],
            ['departamento_id' => '41',    'nombre' => 'Palestina', 'users_id' => 1],
            ['departamento_id' => '41',    'nombre' => 'Pital', 'users_id' => 1],
            ['departamento_id' => '41',    'nombre' => 'Pitalito', 'users_id' => 1],
            ['departamento_id' => '41',    'nombre' => 'Rivera', 'users_id' => 1],
            ['departamento_id' => '41',    'nombre' => 'Saladoblanco', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'Arboleda', 'users_id' => 1],
            ['departamento_id' => '41',    'nombre' => 'Santa María', 'users_id' => 1],
            ['departamento_id' => '41',    'nombre' => 'Suaza', 'users_id' => 1],
            ['departamento_id' => '41',    'nombre' => 'Tarqui', 'users_id' => 1],
            ['departamento_id' => '41',    'nombre' => 'Tesalia', 'users_id' => 1],
            ['departamento_id' => '41',    'nombre' => 'Tello', 'users_id' => 1],
            ['departamento_id' => '41',    'nombre' => 'Teruel', 'users_id' => 1],
            ['departamento_id' => '41',    'nombre' => 'Timaná', 'users_id' => 1],
            ['departamento_id' => '41',    'nombre' => 'Villavieja', 'users_id' => 1],
            ['departamento_id' => '41',    'nombre' => 'Yaguará', 'users_id' => 1],
            ['departamento_id' => '44',    'nombre' => 'Riohacha', 'users_id' => 1],
            ['departamento_id' => '44',    'nombre' => 'Albania', 'users_id' => 1],
            ['departamento_id' => '44',    'nombre' => 'Barrancas', 'users_id' => 1],
            ['departamento_id' => '44',    'nombre' => 'Dibula', 'users_id' => 1],
            ['departamento_id' => '44',    'nombre' => 'Distracción', 'users_id' => 1],
            ['departamento_id' => '44',    'nombre' => 'El Molino', 'users_id' => 1],
            ['departamento_id' => '44',    'nombre' => 'Fonseca', 'users_id' => 1],
            ['departamento_id' => '44',    'nombre' => 'Hatonuevo', 'users_id' => 1],
            ['departamento_id' => '44',    'nombre' => 'Maicao', 'users_id' => 1],
            ['departamento_id' => '44',    'nombre' => 'Manaure', 'users_id' => 1],
            ['departamento_id' => '44',    'nombre' => 'Uribia', 'users_id' => 1],
            ['departamento_id' => '44',    'nombre' => 'Urumita', 'users_id' => 1],
            ['departamento_id' => '44',    'nombre' => 'Villanueva', 'users_id' => 1],
            ['departamento_id' => '47',    'nombre' => 'Santa Marta', 'users_id' => 1],
            ['departamento_id' => '47',    'nombre' => 'Algarrobo', 'users_id' => 1],
            ['departamento_id' => '47',    'nombre' => 'Aracataca', 'users_id' => 1],
            ['departamento_id' => '47',    'nombre' => 'Ariguaní', 'users_id' => 1],
            ['departamento_id' => '47',    'nombre' => 'Cerro San Antonio', 'users_id' => 1],
            ['departamento_id' => '47',    'nombre' => 'Chivolo', 'users_id' => 1],
            ['departamento_id' => '47',    'nombre' => 'Concordia', 'users_id' => 1],
            ['departamento_id' => '47',    'nombre' => 'El Banco', 'users_id' => 1],
            ['departamento_id' => '47',    'nombre' => 'El Piñon', 'users_id' => 1],
            ['departamento_id' => '47',    'nombre' => 'El Retén', 'users_id' => 1],
            ['departamento_id' => '47',    'nombre' => 'Fundación', 'users_id' => 1],
            ['departamento_id' => '47',    'nombre' => 'Guamal', 'users_id' => 1],
            ['departamento_id' => '47',    'nombre' => 'Nueva Granada', 'users_id' => 1],
            ['departamento_id' => '47',    'nombre' => 'Pedraza', 'users_id' => 1],
            ['departamento_id' => '47',    'nombre' => 'Pivijay', 'users_id' => 1],
            ['departamento_id' => '47',    'nombre' => 'Plato', 'users_id' => 1],
            ['departamento_id' => '47',    'nombre' => 'Remolino', 'users_id' => 1],
            ['departamento_id' => '47',    'nombre' => 'Salamina', 'users_id' => 1],
            ['departamento_id' => '47',    'nombre' => 'San Zenón', 'users_id' => 1],
            ['departamento_id' => '47',    'nombre' => 'Santa Ana', 'users_id' => 1],
            ['departamento_id' => '47',    'nombre' => 'Sitionuevo', 'users_id' => 1],
            ['departamento_id' => '47',    'nombre' => 'Tenerife', 'users_id' => 1],
            ['departamento_id' => '47',    'nombre' => 'Zapayán', 'users_id' => 1],
            ['departamento_id' => '47',    'nombre' => 'Zona Bananera', 'users_id' => 1],
            ['departamento_id' => '50',    'nombre' => 'Villavicencio', 'users_id' => 1],
            ['departamento_id' => '50',    'nombre' => 'Acacias', 'users_id' => 1],
            ['departamento_id' => '50',    'nombre' => 'Cabuyaro', 'users_id' => 1],
            ['departamento_id' => '50',    'nombre' => 'Cubarral', 'users_id' => 1],
            ['departamento_id' => '50',    'nombre' => 'Cumaral', 'users_id' => 1],
            ['departamento_id' => '50',    'nombre' => 'El Calvario', 'users_id' => 1],
            ['departamento_id' => '50',    'nombre' => 'El Castillo', 'users_id' => 1],
            ['departamento_id' => '50',    'nombre' => 'El Dorado', 'users_id' => 1],
            ['departamento_id' => '76',    'nombre' => 'Buenaventura', 'users_id' => 1],
            ['departamento_id' => '50',    'nombre' => 'Granada', 'users_id' => 1],
            ['departamento_id' => '50',    'nombre' => 'Guamal', 'users_id' => 1],
            ['departamento_id' => '50',    'nombre' => 'Mapiripán', 'users_id' => 1],
            ['departamento_id' => '50',    'nombre' => 'Mesetas', 'users_id' => 1],
            ['departamento_id' => '50',    'nombre' => 'La Macarena', 'users_id' => 1],
            ['departamento_id' => '50',    'nombre' => 'Uribe', 'users_id' => 1],
            ['departamento_id' => '50',    'nombre' => 'Lejanías', 'users_id' => 1],
            ['departamento_id' => '50',    'nombre' => 'Puerto Concordia', 'users_id' => 1],
            ['departamento_id' => '50',    'nombre' => 'Puerto Gaitán', 'users_id' => 1],
            ['departamento_id' => '50',    'nombre' => 'Puerto López', 'users_id' => 1],
            ['departamento_id' => '50',    'nombre' => 'Puerto Lleras', 'users_id' => 1],
            ['departamento_id' => '50',    'nombre' => 'Puerto Rico', 'users_id' => 1],
            ['departamento_id' => '50',    'nombre' => 'Restrepo', 'users_id' => 1],
            ['departamento_id' => '47',    'nombre' => 'Ciénaga', 'users_id' => 1],
            ['departamento_id' => '8',    'nombre' => 'Ponedera', 'users_id' => 1],
            ['departamento_id' => '50',    'nombre' => 'San Juanito', 'users_id' => 1],
            ['departamento_id' => '50',    'nombre' => 'San Martín', 'users_id' => 1],
            ['departamento_id' => '50',    'nombre' => 'Vista Hermosa', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'Pasto', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'Albán', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'Aldana', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'Ancuyá', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Tununguá', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'Barbacoas', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Motavita', 'users_id' => 1],
            ['departamento_id' => '23',    'nombre' => 'San Bernardo del Viento', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'Colón', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'Consaca', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'Contadero', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'Córdoba', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'Cuaspud', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'Cumbal', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'Cumbitara', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'El Charco', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'El Peñol', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'El Rosario', 'users_id' => 1],
            ['departamento_id' => '27',    'nombre' => 'Istmina', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'El Tambo', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'Funes', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'Guachucal', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'Guaitarilla', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'Gualmatán', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'Iles', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'Imués', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'Ipiales', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'La Cruz', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'La Florida', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'La Llanada', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'La Tola', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'La Unión', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'Leiva', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'Linares', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'Los Andes', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'Magüí', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'Mallama', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'Mosquera', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'Nariño', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'Olaya Herrera', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'Ospina', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'Francisco Pizarro', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'Policarpa', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'Potosí', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'Providencia', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'Puerres', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'Pupiales', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'Ricaurte', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'Roberto Payán', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'Samaniego', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'Sandoná', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'San Bernardo', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'San Lorenzo', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'San Pablo', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Belmira', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Ciénega', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'Santa Bárbara', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'Sapuyes', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'Taminango', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'Tangua', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'Santacruz', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'Túquerres', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'Yacuanquer', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Puerto Wilches', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Puerto Parra', 'users_id' => 1],
            ['departamento_id' => '63',    'nombre' => 'Armenia', 'users_id' => 1],
            ['departamento_id' => '63',    'nombre' => 'Buenavista', 'users_id' => 1],
            ['departamento_id' => '63',    'nombre' => 'Circasia', 'users_id' => 1],
            ['departamento_id' => '63',    'nombre' => 'Córdoba', 'users_id' => 1],
            ['departamento_id' => '63',    'nombre' => 'Filandia', 'users_id' => 1],
            ['departamento_id' => '63',    'nombre' => 'La Tebaida', 'users_id' => 1],
            ['departamento_id' => '63',    'nombre' => 'Montenegro', 'users_id' => 1],
            ['departamento_id' => '63',    'nombre' => 'Pijao', 'users_id' => 1],
            ['departamento_id' => '63',    'nombre' => 'Quimbaya', 'users_id' => 1],
            ['departamento_id' => '63',    'nombre' => 'Salento', 'users_id' => 1],
            ['departamento_id' => '66',    'nombre' => 'Pereira', 'users_id' => 1],
            ['departamento_id' => '66',    'nombre' => 'Apía', 'users_id' => 1],
            ['departamento_id' => '66',    'nombre' => 'Balboa', 'users_id' => 1],
            ['departamento_id' => '66',    'nombre' => 'Dosquebradas', 'users_id' => 1],
            ['departamento_id' => '66',    'nombre' => 'Guática', 'users_id' => 1],
            ['departamento_id' => '66',    'nombre' => 'La Celia', 'users_id' => 1],
            ['departamento_id' => '66',    'nombre' => 'La Virginia', 'users_id' => 1],
            ['departamento_id' => '66',    'nombre' => 'Marsella', 'users_id' => 1],
            ['departamento_id' => '66',    'nombre' => 'Mistrató', 'users_id' => 1],
            ['departamento_id' => '66',    'nombre' => 'Pueblo Rico', 'users_id' => 1],
            ['departamento_id' => '66',    'nombre' => 'Quinchía', 'users_id' => 1],
            ['departamento_id' => '66',    'nombre' => 'Santuario', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Bucaramanga', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Aguada', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Albania', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Aratoca', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Barbosa', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Barichara', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Barrancabermeja', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Betulia', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Bolívar', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Cabrera', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'California', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Carcasí', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Cepitá', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Cerrito', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Charalá', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Charta', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Chipatá', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Cimitarra', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Concepción', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Confines', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Contratación', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Coromoro', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Curití', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'El Guacamayo', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'El Playón', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Encino', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Enciso', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Florián', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Floridablanca', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Galán', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Gambita', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Girón', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Guaca', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Guadalupe', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Guapotá', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Guavatá', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Güepsa', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Jesús María', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Jordán', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'La Belleza', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Landázuri', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'La Paz', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Lebríja', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Los Santos', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Macaravita', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Málaga', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Matanza', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Mogotes', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Molagavita', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Ocamonte', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Oiba', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Onzaga', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Palmar', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Páramo', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Piedecuesta', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Pinchote', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Puente Nacional', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Rionegro', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'San Andrés', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'San Gil', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'San Joaquín', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'San Miguel', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Santa Bárbara', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Simacota', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Socorro', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Suaita', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Sucre', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Suratá', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Tona', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Vélez', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Vetas', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Villanueva', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Zapatoca', 'users_id' => 1],
            ['departamento_id' => '70',    'nombre' => 'Sincelejo', 'users_id' => 1],
            ['departamento_id' => '70',    'nombre' => 'Buenavista', 'users_id' => 1],
            ['departamento_id' => '70',    'nombre' => 'Caimito', 'users_id' => 1],
            ['departamento_id' => '70',    'nombre' => 'Coloso', 'users_id' => 1],
            ['departamento_id' => '70',    'nombre' => 'Coveñas', 'users_id' => 1],
            ['departamento_id' => '70',    'nombre' => 'Chalán', 'users_id' => 1],
            ['departamento_id' => '70',    'nombre' => 'El Roble', 'users_id' => 1],
            ['departamento_id' => '70',    'nombre' => 'Galeras', 'users_id' => 1],
            ['departamento_id' => '70',    'nombre' => 'Guaranda', 'users_id' => 1],
            ['departamento_id' => '70',    'nombre' => 'La Unión', 'users_id' => 1],
            ['departamento_id' => '70',    'nombre' => 'Los Palmitos', 'users_id' => 1],
            ['departamento_id' => '70',    'nombre' => 'Majagual', 'users_id' => 1],
            ['departamento_id' => '70',    'nombre' => 'Morroa', 'users_id' => 1],
            ['departamento_id' => '70',    'nombre' => 'Ovejas', 'users_id' => 1],
            ['departamento_id' => '70',    'nombre' => 'Palmito', 'users_id' => 1],
            ['departamento_id' => '70',    'nombre' => 'San Benito Abad', 'users_id' => 1],
            ['departamento_id' => '70',    'nombre' => 'San Marcos', 'users_id' => 1],
            ['departamento_id' => '70',    'nombre' => 'San Onofre', 'users_id' => 1],
            ['departamento_id' => '70',    'nombre' => 'San Pedro', 'users_id' => 1],
            ['departamento_id' => '70',    'nombre' => 'Sucre', 'users_id' => 1],
            ['departamento_id' => '70',    'nombre' => 'Tolú Viejo', 'users_id' => 1],
            ['departamento_id' => '73',    'nombre' => 'Alpujarra', 'users_id' => 1],
            ['departamento_id' => '73',    'nombre' => 'Alvarado', 'users_id' => 1],
            ['departamento_id' => '73',    'nombre' => 'Ambalema', 'users_id' => 1],
            ['departamento_id' => '73',    'nombre' => 'Armero', 'users_id' => 1],
            ['departamento_id' => '73',    'nombre' => 'Ataco', 'users_id' => 1],
            ['departamento_id' => '73',    'nombre' => 'Cajamarca', 'users_id' => 1],
            ['departamento_id' => '73',    'nombre' => 'Chaparral', 'users_id' => 1],
            ['departamento_id' => '73',    'nombre' => 'Coello', 'users_id' => 1],
            ['departamento_id' => '73',    'nombre' => 'Coyaima', 'users_id' => 1],
            ['departamento_id' => '73',    'nombre' => 'Cunday', 'users_id' => 1],
            ['departamento_id' => '73',    'nombre' => 'Dolores', 'users_id' => 1],
            ['departamento_id' => '73',    'nombre' => 'Espinal', 'users_id' => 1],
            ['departamento_id' => '73',    'nombre' => 'Falan', 'users_id' => 1],
            ['departamento_id' => '73',    'nombre' => 'Flandes', 'users_id' => 1],
            ['departamento_id' => '73',    'nombre' => 'Fresno', 'users_id' => 1],
            ['departamento_id' => '73',    'nombre' => 'Guamo', 'users_id' => 1],
            ['departamento_id' => '73',    'nombre' => 'Herveo', 'users_id' => 1],
            ['departamento_id' => '73',    'nombre' => 'Honda', 'users_id' => 1],
            ['departamento_id' => '73',    'nombre' => 'Icononzo', 'users_id' => 1],
            ['departamento_id' => '73',    'nombre' => 'Mariquita', 'users_id' => 1],
            ['departamento_id' => '73',    'nombre' => 'Melgar', 'users_id' => 1],
            ['departamento_id' => '73',    'nombre' => 'Murillo', 'users_id' => 1],
            ['departamento_id' => '73',    'nombre' => 'Natagaima', 'users_id' => 1],
            ['departamento_id' => '73',    'nombre' => 'Ortega', 'users_id' => 1],
            ['departamento_id' => '73',    'nombre' => 'Palocabildo', 'users_id' => 1],
            ['departamento_id' => '73',    'nombre' => 'Piedras', 'users_id' => 1],
            ['departamento_id' => '73',    'nombre' => 'Planadas', 'users_id' => 1],
            ['departamento_id' => '73',    'nombre' => 'Prado', 'users_id' => 1],
            ['departamento_id' => '73',    'nombre' => 'Purificación', 'users_id' => 1],
            ['departamento_id' => '73',    'nombre' => 'Rio Blanco', 'users_id' => 1],
            ['departamento_id' => '73',    'nombre' => 'Roncesvalles', 'users_id' => 1],
            ['departamento_id' => '73',    'nombre' => 'Rovira', 'users_id' => 1],
            ['departamento_id' => '73',    'nombre' => 'Saldaña', 'users_id' => 1],
            ['departamento_id' => '73',    'nombre' => 'Santa Isabel', 'users_id' => 1],
            ['departamento_id' => '73',    'nombre' => 'Venadillo', 'users_id' => 1],
            ['departamento_id' => '73',    'nombre' => 'Villahermosa', 'users_id' => 1],
            ['departamento_id' => '73',    'nombre' => 'Villarrica', 'users_id' => 1],
            ['departamento_id' => '81',    'nombre' => 'Arauquita', 'users_id' => 1],
            ['departamento_id' => '81',    'nombre' => 'Cravo Norte', 'users_id' => 1],
            ['departamento_id' => '81',    'nombre' => 'Fortul', 'users_id' => 1],
            ['departamento_id' => '81',    'nombre' => 'Puerto Rondón', 'users_id' => 1],
            ['departamento_id' => '81',    'nombre' => 'Saravena', 'users_id' => 1],
            ['departamento_id' => '81',    'nombre' => 'Tame', 'users_id' => 1],
            ['departamento_id' => '81',    'nombre' => 'Arauca', 'users_id' => 1],
            ['departamento_id' => '85',    'nombre' => 'Yopal', 'users_id' => 1],
            ['departamento_id' => '85',    'nombre' => 'Aguazul', 'users_id' => 1],
            ['departamento_id' => '85',    'nombre' => 'Chámeza', 'users_id' => 1],
            ['departamento_id' => '85',    'nombre' => 'Hato Corozal', 'users_id' => 1],
            ['departamento_id' => '85',    'nombre' => 'La Salina', 'users_id' => 1],
            ['departamento_id' => '85',    'nombre' => 'Monterrey', 'users_id' => 1],
            ['departamento_id' => '85',    'nombre' => 'Pore', 'users_id' => 1],
            ['departamento_id' => '85',    'nombre' => 'Recetor', 'users_id' => 1],
            ['departamento_id' => '85',    'nombre' => 'Sabanalarga', 'users_id' => 1],
            ['departamento_id' => '85',    'nombre' => 'Sácama', 'users_id' => 1],
            ['departamento_id' => '85',    'nombre' => 'Tauramena', 'users_id' => 1],
            ['departamento_id' => '85',    'nombre' => 'Trinidad', 'users_id' => 1],
            ['departamento_id' => '85',    'nombre' => 'Villanueva', 'users_id' => 1],
            ['departamento_id' => '86',    'nombre' => 'Mocoa', 'users_id' => 1],
            ['departamento_id' => '86',    'nombre' => 'Colón', 'users_id' => 1],
            ['departamento_id' => '86',    'nombre' => 'Orito', 'users_id' => 1],
            ['departamento_id' => '86',    'nombre' => 'Puerto Caicedo', 'users_id' => 1],
            ['departamento_id' => '86',    'nombre' => 'Puerto Guzmán', 'users_id' => 1],
            ['departamento_id' => '86',    'nombre' => 'Leguízamo', 'users_id' => 1],
            ['departamento_id' => '86',    'nombre' => 'Sibundoy', 'users_id' => 1],
            ['departamento_id' => '86',    'nombre' => 'San Francisco', 'users_id' => 1],
            ['departamento_id' => '86',    'nombre' => 'San Miguel', 'users_id' => 1],
            ['departamento_id' => '86',    'nombre' => 'Santiago', 'users_id' => 1],
            ['departamento_id' => '91',    'nombre' => 'Leticia', 'users_id' => 1],
            ['departamento_id' => '91',    'nombre' => 'El Encanto', 'users_id' => 1],
            ['departamento_id' => '91',    'nombre' => 'La Chorrera', 'users_id' => 1],
            ['departamento_id' => '91',    'nombre' => 'La Pedrera', 'users_id' => 1],
            ['departamento_id' => '91',    'nombre' => 'La Victoria', 'users_id' => 1],
            ['departamento_id' => '91',    'nombre' => 'Puerto Arica', 'users_id' => 1],
            ['departamento_id' => '91',    'nombre' => 'Puerto Nariño', 'users_id' => 1],
            ['departamento_id' => '91',    'nombre' => 'Puerto Santander', 'users_id' => 1],
            ['departamento_id' => '91',    'nombre' => 'Tarapacá', 'users_id' => 1],
            ['departamento_id' => '94',    'nombre' => 'Inírida', 'users_id' => 1],
            ['departamento_id' => '94',    'nombre' => 'Barranco Minas', 'users_id' => 1],
            ['departamento_id' => '94',    'nombre' => 'Mapiripana', 'users_id' => 1],
            ['departamento_id' => '94',    'nombre' => 'San Felipe', 'users_id' => 1],
            ['departamento_id' => '94',    'nombre' => 'Puerto Colombia', 'users_id' => 1],
            ['departamento_id' => '94',    'nombre' => 'La Guadalupe', 'users_id' => 1],
            ['departamento_id' => '94',    'nombre' => 'Cacahual', 'users_id' => 1],
            ['departamento_id' => '94',    'nombre' => 'Pana Pana', 'users_id' => 1],
            ['departamento_id' => '94',    'nombre' => 'Morichal', 'users_id' => 1],
            ['departamento_id' => '97',    'nombre' => 'Mitú', 'users_id' => 1],
            ['departamento_id' => '97',    'nombre' => 'Caruru', 'users_id' => 1],
            ['departamento_id' => '97',    'nombre' => 'Pacoa', 'users_id' => 1],
            ['departamento_id' => '97',    'nombre' => 'Taraira', 'users_id' => 1],
            ['departamento_id' => '97',    'nombre' => 'Papunaua', 'users_id' => 1],
            ['departamento_id' => '99',    'nombre' => 'Puerto Carreño', 'users_id' => 1],
            ['departamento_id' => '99',    'nombre' => 'La Primavera', 'users_id' => 1],
            ['departamento_id' => '99',    'nombre' => 'Santa Rosalía', 'users_id' => 1],
            ['departamento_id' => '99',    'nombre' => 'Cumaribo', 'users_id' => 1],
            ['departamento_id' => '18',    'nombre' => 'San José del Fragua', 'users_id' => 1],
            ['departamento_id' => '50',    'nombre' => 'Barranca de Upía', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Palmas del Socorro', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'San Juan de Río Seco', 'users_id' => 1],
            ['departamento_id' => '8',    'nombre' => 'Juan de Acosta', 'users_id' => 1],
            ['departamento_id' => '50',    'nombre' => 'Fuente de Oro', 'users_id' => 1],
            ['departamento_id' => '85',    'nombre' => 'San Luis de Gaceno', 'users_id' => 1],
            ['departamento_id' => '27',    'nombre' => 'El Litoral del San Juan', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Villa de San Diego de Ubate', 'users_id' => 1],
            ['departamento_id' => '13',    'nombre' => 'Barranco de Loba', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Togüí', 'users_id' => 1],
            ['departamento_id' => '13',    'nombre' => 'Santa Rosa del Sur', 'users_id' => 1],
            ['departamento_id' => '27',    'nombre' => 'El Cantón del San Pablo', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Villa de Leyva', 'users_id' => 1],
            ['departamento_id' => '47',    'nombre' => 'San Sebastián de Buenavista', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Paz de Río', 'users_id' => 1],
            ['departamento_id' => '13',    'nombre' => 'Hatillo de Loba', 'users_id' => 1],
            ['departamento_id' => '47',    'nombre' => 'Sabanas de San Angel', 'users_id' => 1],
            ['departamento_id' => '95',    'nombre' => 'Calamar', 'users_id' => 1],
            ['departamento_id' => '20',    'nombre' => 'Río de Oro', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'San Pedro de Uraba', 'users_id' => 1],
            ['departamento_id' => '95',    'nombre' => 'San José del Guaviare', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Santa Rosa de Viterbo', 'users_id' => 1],
            ['departamento_id' => '19',    'nombre' => 'Santander de Quilichao', 'users_id' => 1],
            ['departamento_id' => '95',    'nombre' => 'Miraflores', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Santafé de Antioquia', 'users_id' => 1],
            ['departamento_id' => '50',    'nombre' => 'San Carlos de Guaroa', 'users_id' => 1],
            ['departamento_id' => '8',    'nombre' => 'Palmar de Varela', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Santa Rosa de Osos', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'San Andrés de Cuerquía', 'users_id' => 1],
            ['departamento_id' => '73',    'nombre' => 'Valle de San Juan', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'San Vicente de Chucurí', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'San José de Miranda', 'users_id' => 1],
            ['departamento_id' => '88',    'nombre' => 'Providencia', 'users_id' => 1],
            ['departamento_id' => '66',    'nombre' => 'Santa Rosa de Cabal', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Guayabal de Siquima', 'users_id' => 1],
            ['departamento_id' => '18',    'nombre' => 'Belén de Los Andaquies', 'users_id' => 1],
            ['departamento_id' => '85',    'nombre' => 'Paz de Ariporo', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Santa Helena del Opón', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'San Pablo de Borbur', 'users_id' => 1],
            ['departamento_id' => '44',    'nombre' => 'La Jagua del Pilar', 'users_id' => 1],
            ['departamento_id' => '20',    'nombre' => 'La Jagua de Ibirico', 'users_id' => 1],
            ['departamento_id' => '70',    'nombre' => 'San Luis de Sincé', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'San Luis de Gaceno', 'users_id' => 1],
            ['departamento_id' => '13',    'nombre' => 'El Carmen de Bolívar', 'users_id' => 1],
            ['departamento_id' => '27',    'nombre' => 'El Carmen de Atrato', 'users_id' => 1],
            ['departamento_id' => '70',    'nombre' => 'San Juan de Betulia', 'users_id' => 1],
            ['departamento_id' => '47',    'nombre' => 'Pijiño del Carmen', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'Vigía del Fuerte', 'users_id' => 1],
            ['departamento_id' => '13',    'nombre' => 'San Martín de Loba', 'users_id' => 1],
            ['departamento_id' => '13',    'nombre' => 'Altos del Rosario', 'users_id' => 1],
            ['departamento_id' => '73',    'nombre' => 'Carmen de Apicala', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'San Antonio del Tequendama', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Sabana de Torres', 'users_id' => 1],
            ['departamento_id' => '95',    'nombre' => 'El Retorno', 'users_id' => 1],
            ['departamento_id' => '23',    'nombre' => 'San José de Uré', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'San Pedro de Cartago', 'users_id' => 1],
            ['departamento_id' => '8',    'nombre' => 'Campo de La Cruz', 'users_id' => 1],
            ['departamento_id' => '50',    'nombre' => 'San Juan de Arama', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'San José de La Montaña', 'users_id' => 1],
            ['departamento_id' => '18',    'nombre' => 'Cartagena del Chairá', 'users_id' => 1],
            ['departamento_id' => '27',    'nombre' => 'San José del Palmar', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Agua de Dios', 'users_id' => 1],
            ['departamento_id' => '13',    'nombre' => 'San Jacinto del Cauca', 'users_id' => 1],
            ['departamento_id' => '41',    'nombre' => 'San Agustín', 'users_id' => 1],
            ['departamento_id' => '52',    'nombre' => 'El Tablón de Gómez', 'users_id' => 1],
            ['departamento_id' => '88',    'nombre' => 'San Andrés', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'San José de Pare', 'users_id' => 1],
            ['departamento_id' => '86',    'nombre' => 'Valle de Guamez', 'users_id' => 1],
            ['departamento_id' => '13',    'nombre' => 'San Pablo de Borbur', 'users_id' => 1],
            ['departamento_id' => '70',    'nombre' => 'Santiago de Tolú', 'users_id' => 1],
            ['departamento_id' => '11',    'nombre' => 'Bogotá D.C.', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Carmen de Carupa', 'users_id' => 1],
            ['departamento_id' => '23',    'nombre' => 'Ciénaga de Oro', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'San Juan de Urabá', 'users_id' => 1],
            ['departamento_id' => '44',    'nombre' => 'San Juan del Cesar', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'El Carmen de Chucurí', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'El Carmen de Viboral', 'users_id' => 1],
            ['departamento_id' => '66',    'nombre' => 'Belén de Umbría', 'users_id' => 1],
            ['departamento_id' => '27',    'nombre' => 'Belén de Bajira', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Valle de San José', 'users_id' => 1],
            ['departamento_id' => '73',    'nombre' => 'San Luis', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'San Miguel de Sema', 'users_id' => 1],
            ['departamento_id' => '73',    'nombre' => 'San Antonio', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'San Benito', 'users_id' => 1],
            ['departamento_id' => '25',    'nombre' => 'Vergara', 'users_id' => 1],
            ['departamento_id' => '23',    'nombre' => 'San Carlos', 'users_id' => 1],
            ['departamento_id' => '91',    'nombre' => 'Puerto Alegría', 'users_id' => 1],
            ['departamento_id' => '68',    'nombre' => 'Hato', 'users_id' => 1],
            ['departamento_id' => '13',    'nombre' => 'San Jacinto', 'users_id' => 1],
            ['departamento_id' => '19',    'nombre' => 'San Sebastián', 'users_id' => 1],
            ['departamento_id' => '5',    'nombre' => 'San Carlos', 'users_id' => 1],
            ['departamento_id' => '15',    'nombre' => 'Tuta', 'users_id' => 1],
            ['departamento_id' => '54',    'nombre' => 'Silos', 'users_id' => 1],
            ['departamento_id' => '54',    'nombre' => 'Cácota', 'users_id' => 1],
            ['departamento_id' => '76',    'nombre' => 'El Dovio', 'users_id' => 1],
            ['departamento_id' => '54',    'nombre' => 'Toledo', 'users_id' => 1],
            ['departamento_id' => '76',    'nombre' => 'Roldanillo', 'users_id' => 1],
            ['departamento_id' => '54',    'nombre' => 'Mutiscua', 'users_id' => 1],
            ['departamento_id' => '76',    'nombre' => 'Argelia', 'users_id' => 1],
            ['departamento_id' => '54',    'nombre' => 'El Zulia', 'users_id' => 1],
            ['departamento_id' => '54',    'nombre' => 'Salazar', 'users_id' => 1],
            ['departamento_id' => '76',    'nombre' => 'Sevilla', 'users_id' => 1],
            ['departamento_id' => '76',    'nombre' => 'Zarzal', 'users_id' => 1],
            ['departamento_id' => '54',    'nombre' => 'Cucutilla', 'users_id' => 1],
            ['departamento_id' => '76',    'nombre' => 'El Cerrito', 'users_id' => 1],
            ['departamento_id' => '76',    'nombre' => 'Cartago', 'users_id' => 1],
            ['departamento_id' => '76',    'nombre' => 'Caicedonia', 'users_id' => 1],
            ['departamento_id' => '54',    'nombre' => 'Puerto Santander', 'users_id' => 1],
            ['departamento_id' => '54',    'nombre' => 'Gramalote', 'users_id' => 1],
            ['departamento_id' => '76',    'nombre' => 'El Cairo', 'users_id' => 1],
            ['departamento_id' => '54',    'nombre' => 'El Tarra', 'users_id' => 1],
            ['departamento_id' => '76',    'nombre' => 'La Unión', 'users_id' => 1],
            ['departamento_id' => '76',    'nombre' => 'Restrepo', 'users_id' => 1],
            ['departamento_id' => '54',    'nombre' => 'Teorama', 'users_id' => 1],
            ['departamento_id' => '76',    'nombre' => 'Dagua', 'users_id' => 1],
            ['departamento_id' => '54',    'nombre' => 'Arboledas', 'users_id' => 1],
            ['departamento_id' => '76',    'nombre' => 'Guacarí', 'users_id' => 1],
            ['departamento_id' => '54',    'nombre' => 'Lourdes', 'users_id' => 1],
            ['departamento_id' => '76',    'nombre' => 'Ansermanuevo', 'users_id' => 1],
            ['departamento_id' => '54',    'nombre' => 'Bochalema', 'users_id' => 1],
            ['departamento_id' => '76',    'nombre' => 'Bugalagrande', 'users_id' => 1],
            ['departamento_id' => '54',    'nombre' => 'Convención', 'users_id' => 1],
            ['departamento_id' => '54',    'nombre' => 'Hacarí', 'users_id' => 1],
            ['departamento_id' => '76',    'nombre' => 'La Victoria', 'users_id' => 1],
            ['departamento_id' => '54',    'nombre' => 'Herrán', 'users_id' => 1],
            ['departamento_id' => '76',    'nombre' => 'Ginebra', 'users_id' => 1],
            ['departamento_id' => '76',    'nombre' => 'Yumbo', 'users_id' => 1],
            ['departamento_id' => '76',    'nombre' => 'Obando', 'users_id' => 1],
            ['departamento_id' => '54',    'nombre' => 'Tibú', 'users_id' => 1],
            ['departamento_id' => '54',    'nombre' => 'San Cayetano', 'users_id' => 1],
            ['departamento_id' => '54',    'nombre' => 'San Calixto', 'users_id' => 1],
            ['departamento_id' => '76',    'nombre' => 'Bolívar', 'users_id' => 1],
            ['departamento_id' => '54',    'nombre' => 'La Playa', 'users_id' => 1],
            ['departamento_id' => '76',    'nombre' => 'Cali', 'users_id' => 1],
            ['departamento_id' => '76',    'nombre' => 'San Pedro', 'users_id' => 1],
            ['departamento_id' => '76',    'nombre' => 'Guadalajara de Buga', 'users_id' => 1],
            ['departamento_id' => '54',    'nombre' => 'Chinácota', 'users_id' => 1],
            ['departamento_id' => '54',    'nombre' => 'Ragonvalia', 'users_id' => 1],
            ['departamento_id' => '54',    'nombre' => 'La Esperanza', 'users_id' => 1],
            ['departamento_id' => '54',    'nombre' => 'Villa del Rosario', 'users_id' => 1],
            ['departamento_id' => '54',    'nombre' => 'Chitagá', 'users_id' => 1],
            ['departamento_id' => '76',    'nombre' => 'Calima', 'users_id' => 1],
            ['departamento_id' => '54',    'nombre' => 'Sardinata', 'users_id' => 1],
            ['departamento_id' => '76',    'nombre' => 'Andalucía', 'users_id' => 1],
            ['departamento_id' => '76',    'nombre' => 'Pradera', 'users_id' => 1],
            ['departamento_id' => '54',    'nombre' => 'Abrego', 'users_id' => 1],
            ['departamento_id' => '54',    'nombre' => 'Los Patios', 'users_id' => 1],
            ['departamento_id' => '54',    'nombre' => 'Ocaña', 'users_id' => 1],
            ['departamento_id' => '54',    'nombre' => 'Bucarasica', 'users_id' => 1],
            ['departamento_id' => '76',    'nombre' => 'Yotoco', 'users_id' => 1],
            ['departamento_id' => '76',    'nombre' => 'Palmira', 'users_id' => 1],
            ['departamento_id' => '76',    'nombre' => 'Riofrío', 'users_id' => 1],
            ['departamento_id' => '54',    'nombre' => 'Santiago', 'users_id' => 1],
            ['departamento_id' => '76',    'nombre' => 'Alcalá', 'users_id' => 1],
            ['departamento_id' => '76',    'nombre' => 'Versalles', 'users_id' => 1],
            ['departamento_id' => '54',    'nombre' => 'Labateca', 'users_id' => 1],
            ['departamento_id' => '54',    'nombre' => 'Cachirá', 'users_id' => 1],
            ['departamento_id' => '54',    'nombre' => 'Villa Caro', 'users_id' => 1],
            ['departamento_id' => '54',    'nombre' => 'Durania', 'users_id' => 1],
            ['departamento_id' => '76',    'nombre' => 'El Águila', 'users_id' => 1],
            ['departamento_id' => '76',    'nombre' => 'Toro', 'users_id' => 1],
            ['departamento_id' => '76',    'nombre' => 'Candelaria', 'users_id' => 1],
            ['departamento_id' => '76',    'nombre' => 'La Cumbre', 'users_id' => 1],
            ['departamento_id' => '76',    'nombre' => 'Ulloa', 'users_id' => 1],
            ['departamento_id' => '76',    'nombre' => 'Trujillo', 'users_id' => 1],
            ['departamento_id' => '76',    'nombre' => 'Vijes', 'users_id' => 1],           
        ]);
    }
}
